In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s5e10/sample_submission.csv
/kaggle/input/playground-series-s5e10/train.csv
/kaggle/input/playground-series-s5e10/test.csv

In [3]:
from sklearn.compose import make_column_selector, ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

In [4]:
data = pd.read_csv('/kaggle/input/playground-series-s5e10/train.csv')
data.drop(['id'], inplace=True, axis=1)

In [6]:
data.head()

,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56

In [7]:
data.isnull().sum()

road_type                 0
num_lanes                 0
curvature                 0
speed_limit               0
lighting                  0
weather                   0
road_signs_present        0
public_road               0
time_of_day               0
holiday                   0
school_season             0
num_reported_accidents    0
accident_risk             0
dtype: int64

In [8]:
num_cols = make_column_selector(dtype_include='number')
cat_cols = make_column_selector(dtype_include=['object', 'bool'])

In [9]:
data[num_cols].columns

Index(['num_lanes', 'curvature', 'speed_limit', 'num_reported_accidents',
       'accident_risk'],
      dtype='object')

In [10]:
data[cat_cols].columns

Index(['road_type', 'lighting', 'weather', 'road_signs_present', 'public_road',
       'time_of_day', 'holiday', 'school_season'],
      dtype='object')

In [11]:
X = data.drop(['accident_risk'], axis=1)
y = data['accident_risk'].values

In [12]:
cat_pipe = Pipeline([
    ('cat', OneHotEncoder())
])

num_pipe = Pipeline([
    ('num', StandardScaler())
])

ctx = ColumnTransformer([
    ('cat', cat_pipe, cat_cols),
    ('num', num_pipe, num_cols)
], remainder='passthrough')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = ctx.fit_transform(X_train)
X_test = ctx.transform(X_test)

In [13]:
'''
lgbm = LGBMRegressor(objective='binary')
lgbm.fit(X_train, y_train)
y_pred = lgbm.predict(X_test)

print('MSE for lgbm:', mean_squared_error(y_test, y_pred))
print('R2 for lgbm:', r2_score(y_test, y_pred))
'''

"\nlgbm = LGBMRegressor(objective='binary')\nlgbm.fit(X_train, y_train)\ny_pred = lgbm.predict(X_test)\n\nprint('MSE for lgbm:', mean_squared_error(y_test, y_pred))\nprint('R2 for lgbm:', r2_score(y_test, y_pred))\n"

In [14]:
cat = CatBoostRegressor(verbose=0)
cat.fit(X_train, y_train)
y_pred = cat.predict(X_test)

print('MSE for catboost:', mean_squared_error(y_test, y_pred))
print('R2 for catboost:', r2_score(y_test, y_pred))

MSE for catboost: 0.0031612873982016193
R2 for catboost: 0.8855111850975814

In [15]:
param_distributions = {
    'iterations': [200, 400, 800, 1200, 1600],
    'learning_rate': [0.01, 0.03, 0.05, 0.1, 0.2],
    'depth': [4, 5, 6, 7, 8, 9, 10],
    'l2_leaf_reg': [1, 3, 5, 7, 9, 11, 13],
    'bagging_temperature': [0, 0.25, 0.5, 0.75, 1.0],
    'border_count': [32, 64, 128, 254],
    'random_strength': [0.5, 1, 2, 5, 10],
    'leaf_estimation_iterations': [1, 3, 5, 7, 9],
    'grow_policy': ['SymmetricTree', 'Depthwise', 'Lossguide'],
    'bootstrap_type': ['Bayesian', 'Bernoulli', 'MVS'],
    'subsample': [0.6, 0.8, 1.0],
    'min_data_in_leaf': [1, 5, 10, 20, 50, 100]
}

randomCv = RandomizedSearchCV(
    estimator=CatBoostRegressor(verbose=0),
    param_distributions=param_distributions,
    cv = 5,
    n_iter=50,
    scoring='neg_mean_squared_error',
    random_state=42,
    n_jobs=-1
)

ctx2 = ColumnTransformer([
    ('cat', cat_pipe, cat_cols),
    ('num', num_pipe, num_cols)
], remainder='passthrough')

X_transformed = ctx2.fit_transform(X)
gcv = randomCv.fit(X_transformed, y, verbose=1)

0:	learn: 0.1621733	total: 243ms	remaining: 4m 50s
1:	learn: 0.1580769	total: 389ms	remaining: 3m 53s
2:	learn: 0.1541204	total: 517ms	remaining: 3m 26s
3:	learn: 0.1503055	total: 590ms	remaining: 2m 56s
4:	learn: 0.1466196	total: 710ms	remaining: 2m 49s
5:	learn: 0.1430455	total: 836ms	remaining: 2m 46s
6:	learn: 0.1396143	total: 925ms	remaining: 2m 37s
7:	learn: 0.1362958	total: 1.05s	remaining: 2m 36s
8:	learn: 0.1330931	total: 1.19s	remaining: 2m 37s
9:	learn: 0.1300058	total: 1.32s	remaining: 2m 37s
10:	learn: 0.1270236	total: 1.47s	remaining: 2m 38s
11:	learn: 0.1241467	total: 1.63s	remaining: 2m 40s
12:	learn: 0.1213781	total: 1.81s	remaining: 2m 45s
13:	learn: 0.1187078	total: 2.01s	remaining: 2m 50s
14:	learn: 0.1161237	total: 2.17s	remaining: 2m 51s
15:	learn: 0.1136384	total: 2.27s	remaining: 2m 47s
16:	learn: 0.1112457	total: 2.37s	remaining: 2m 45s
17:	learn: 0.1089434	total: 2.56s	remaining: 2m 47s
18:	learn: 0.1067241	total: 2.73s	remaining: 2m 49s
19:	learn: 0.1045918	total: 2.92s	remaining: 2m 52s
20:	learn: 0.1025419	total: 3.09s	remaining: 2m 53s
21:	learn: 0.1005746	total: 3.29s	remaining: 2m 56s
22:	learn: 0.0986752	total: 3.44s	remaining: 2m 55s
23:	learn: 0.0968535	total: 3.6s	remaining: 2m 56s
24:	learn: 0.0950983	total: 3.82s	remaining: 2m 59s
25:	learn: 0.0933964	total: 4.01s	remaining: 3m 1s
26:	learn: 0.0917123	total: 4.25s	remaining: 3m 4s
27:	learn: 0.0900969	total: 4.5s	remaining: 3m 8s
28:	learn: 0.0885963	total: 4.69s	remaining: 3m 9s
29:	learn: 0.0871130	total: 4.88s	remaining: 3m 10s
30:	learn: 0.0856929	total: 5.05s	remaining: 3m 10s
31:	learn: 0.0843349	total: 5.24s	remaining: 3m 11s
32:	learn: 0.0830373	total: 5.46s	remaining: 3m 13s
33:	learn: 0.0817976	total: 5.67s	remaining: 3m 14s
34:	learn: 0.0806125	total: 5.9s	remaining: 3m 16s
35:	learn: 0.0794813	total: 6.11s	remaining: 3m 17s
36:	learn: 0.0784067	total: 6.29s	remaining: 3m 17s
37:	learn: 0.0773687	total: 6.55s	remaining: 3m 20s
38:	learn: 0.0763725	total: 6.75s	remaining: 3m 20s
39:	learn: 0.0754279	total: 6.94s	remaining: 3m 21s
40:	learn: 0.0745246	total: 7.15s	remaining: 3m 22s
41:	learn: 0.0736634	total: 7.46s	remaining: 3m 25s
42:	learn: 0.0728476	total: 7.67s	remaining: 3m 26s
43:	learn: 0.0720537	total: 7.9s	remaining: 3m 27s
44:	learn: 0.0712990	total: 8.16s	remaining: 3m 29s
45:	learn: 0.0705812	total: 8.44s	remaining: 3m 31s
46:	learn: 0.0698960	total: 8.67s	remaining: 3m 32s
47:	learn: 0.0692431	total: 8.87s	remaining: 3m 32s
48:	learn: 0.0686211	total: 9.04s	remaining: 3m 32s
49:	learn: 0.0680286	total: 9.17s	remaining: 3m 30s
50:	learn: 0.0674688	total: 9.36s	remaining: 3m 30s
51:	learn: 0.0669340	total: 9.55s	remaining: 3m 30s
52:	learn: 0.0664194	total: 9.8s	remaining: 3m 32s
53:	learn: 0.0659316	total: 10s	remaining: 3m 32s
54:	learn: 0.0654683	total: 10.2s	remaining: 3m 32s
55:	learn: 0.0650276	total: 10.5s	remaining: 3m 33s
56:	learn: 0.0646057	total: 10.7s	remaining: 3m 33s
57:	learn: 0.0642078	total: 10.9s	remaining: 3m 33s
58:	learn: 0.0638275	total: 11.1s	remaining: 3m 34s
59:	learn: 0.0634681	total: 11.3s	remaining: 3m 35s
60:	learn: 0.0631261	total: 11.6s	remaining: 3m 35s
61:	learn: 0.0627981	total: 11.8s	remaining: 3m 36s
62:	learn: 0.0624895	total: 12s	remaining: 3m 37s
63:	learn: 0.0621956	total: 12.2s	remaining: 3m 36s
64:	learn: 0.0619148	total: 12.4s	remaining: 3m 36s
65:	learn: 0.0616496	total: 12.6s	remaining: 3m 36s
66:	learn: 0.0613974	total: 12.8s	remaining: 3m 36s
67:	learn: 0.0611580	total: 13s	remaining: 3m 36s
68:	learn: 0.0609315	total: 13.2s	remaining: 3m 36s
69:	learn: 0.0607174	total: 13.4s	remaining: 3m 36s
70:	learn: 0.0605139	total: 13.7s	remaining: 3m 37s
71:	learn: 0.0603202	total: 13.9s	remaining: 3m 37s
72:	learn: 0.0601363	total: 14.1s	remaining: 3m 37s
73:	learn: 0.0599613	total: 14.2s	remaining: 3m 36s
74:	learn: 0.0597961	total: 14.5s	remaining: 3m 37s
75:	learn: 0.0596394	total: 14.7s	remaining: 3m 37s
76:	learn: 0.0594918	total: 15s	remaining: 3m 38s
77:	learn: 0.0593503	total: 15.3s	remaining: 3m 39s
78:	learn: 0.0592184	total: 15.5s	remaining: 3m 40s
79:	learn: 0.0590924	total: 15.7s	remaining: 3m 40s
80:	learn: 0.0589740	total: 15.9s	remaining: 3m 40s
81:	learn: 0.0588588	total: 16.2s	remaining: 3m 40s
82:	learn: 0.0587500	total: 16.4s	remaining: 3m 40s
83:	learn: 0.0586449	total: 16.6s	remaining: 3m 41s
84:	learn: 0.0585476	total: 16.9s	remaining: 3m 41s
85:	learn: 0.0584543	total: 17.2s	remaining: 3m 42s
86:	learn: 0.0583675	total: 17.5s	remaining: 3m 43s
87:	learn: 0.0582833	total: 17.7s	remaining: 3m 43s
88:	learn: 0.0582036	total: 18s	remaining: 3m 44s
89:	learn: 0.0581292	total: 18.2s	remaining: 3m 44s
90:	learn: 0.0580585	total: 18.5s	remaining: 3m 45s
91:	learn: 0.0579901	total: 18.8s	remaining: 3m 46s
92:	learn: 0.0579269	total: 19s	remaining: 3m 46s
93:	learn: 0.0578666	total: 19.3s	remaining: 3m 46s
94:	learn: 0.0578103	total: 19.5s	remaining: 3m 47s
95:	learn: 0.0577552	total: 19.9s	remaining: 3m 48s
96:	learn: 0.0577029	total: 20.1s	remaining: 3m 48s
97:	learn: 0.0576538	total: 20.3s	remaining: 3m 48s
98:	learn: 0.0576076	total: 20.5s	remaining: 3m 48s
99:	learn: 0.0575628	total: 20.7s	remaining: 3m 47s
100:	learn: 0.0575197	total: 21s	remaining: 3m 48s
101:	learn: 0.0574790	total: 21.3s	remaining: 3m 49s
102:	learn: 0.0574414	total: 21.6s	remaining: 3m 49s
103:	learn: 0.0574052	total: 21.7s	remaining: 3m 48s
104:	learn: 0.0573699	total: 22s	remaining: 3m 49s
105:	learn: 0.0573372	total: 22.2s	remaining: 3m 49s
106:	learn: 0.0573057	total: 22.5s	remaining: 3m 49s
107:	learn: 0.0572762	total: 22.7s	remaining: 3m 50s
108:	learn: 0.0572477	total: 23s	remaining: 3m 49s
109:	learn: 0.0572214	total: 23.2s	remaining: 3m 49s
110:	learn: 0.0571946	total: 23.4s	remaining: 3m 49s
111:	learn: 0.0571704	total: 23.7s	remaining: 3m 50s
112:	learn: 0.0571473	total: 23.9s	remaining: 3m 49s
113:	learn: 0.0571258	total: 24.1s	remaining: 3m 49s
114:	learn: 0.0571048	total: 24.3s	remaining: 3m 49s
115:	learn: 0.0570836	total: 24.6s	remaining: 3m 49s
116:	learn: 0.0570635	total: 24.8s	remaining: 3m 49s
117:	learn: 0.0570449	total: 25s	remaining: 3m 49s
118:	learn: 0.0570260	total: 25.3s	remaining: 3m 49s
119:	learn: 0.0570071	total: 25.5s	remaining: 3m 49s
120:	learn: 0.0569909	total: 25.6s	remaining: 3m 48s
121:	learn: 0.0569741	total: 25.7s	remaining: 3m 47s
122:	learn: 0.0569582	total: 26s	remaining: 3m 47s
123:	learn: 0.0569428	total: 26.3s	remaining: 3m 47s
124:	learn: 0.0569288	total: 26.5s	remaining: 3m 48s
125:	learn: 0.0569156	total: 26.7s	remaining: 3m 47s
126:	learn: 0.0569025	total: 26.9s	remaining: 3m 47s
127:	learn: 0.0568906	total: 27.1s	remaining: 3m 47s
128:	learn: 0.0568785	total: 27.5s	remaining: 3m 48s
129:	learn: 0.0568658	total: 27.7s	remaining: 3m 47s
130:	learn: 0.0568539	total: 27.9s	remaining: 3m 47s
131:	learn: 0.0568428	total: 28.2s	remaining: 3m 48s
132:	learn: 0.0568325	total: 28.4s	remaining: 3m 48s
133:	learn: 0.0568201	total: 28.6s	remaining: 3m 47s
134:	learn: 0.0568105	total: 28.8s	remaining: 3m 47s
135:	learn: 0.0568007	total: 29.1s	remaining: 3m 47s
136:	learn: 0.0567919	total: 29.2s	remaining: 3m 46s
137:	learn: 0.0567809	total: 29.5s	remaining: 3m 47s
138:	learn: 0.0567728	total: 29.8s	remaining: 3m 47s
139:	learn: 0.0567646	total: 30s	remaining: 3m 47s
140:	learn: 0.0567571	total: 30.2s	remaining: 3m 46s
141:	learn: 0.0567503	total: 30.4s	remaining: 3m 46s
142:	learn: 0.0567434	total: 30.6s	remaining: 3m 46s
143:	learn: 0.0567355	total: 30.9s	remaining: 3m 46s
144:	learn: 0.0567263	total: 31.1s	remaining: 3m 46s
145:	learn: 0.0567185	total: 31.2s	remaining: 3m 45s
146:	learn: 0.0567114	total: 31.5s	remaining: 3m 45s
147:	learn: 0.0567047	total: 31.8s	remaining: 3m 46s
148:	learn: 0.0566965	total: 32s	remaining: 3m 46s
149:	learn: 0.0566902	total: 32.2s	remaining: 3m 45s
150:	learn: 0.0566844	total: 32.4s	remaining: 3m 45s
151:	learn: 0.0566772	total: 32.7s	remaining: 3m 45s
152:	learn: 0.0566713	total: 32.9s	remaining: 3m 45s
153:	learn: 0.0566646	total: 33.1s	remaining: 3m 45s
154:	learn: 0.0566597	total: 33.4s	remaining: 3m 44s
155:	learn: 0.0566543	total: 33.6s	remaining: 3m 44s
156:	learn: 0.0566494	total: 33.8s	remaining: 3m 44s
157:	learn: 0.0566442	total: 34.1s	remaining: 3m 44s
0:	learn: 0.1622208	total: 295ms	remaining: 5m 53s
1:	learn: 0.1581278	total: 442ms	remaining: 4m 24s
2:	learn: 0.1541775	total: 627ms	remaining: 4m 10s
3:	learn: 0.1503638	total: 857ms	remaining: 4m 16s
4:	learn: 0.1466790	total: 1.08s	remaining: 4m 17s
5:	learn: 0.1431198	total: 1.34s	remaining: 4m 26s
6:	learn: 0.1396877	total: 1.59s	remaining: 4m 31s
7:	learn: 0.1363753	total: 1.8s	remaining: 4m 29s
8:	learn: 0.1331709	total: 2.03s	remaining: 4m 28s
9:	learn: 0.1300879	total: 2.28s	remaining: 4m 31s
10:	learn: 0.1270966	total: 2.53s	remaining: 4m 33s
11:	learn: 0.1242250	total: 2.81s	remaining: 4m 38s
12:	learn: 0.1214463	total: 3.11s	remaining: 4m 44s
13:	learn: 0.1187749	total: 3.33s	remaining: 4m 42s
14:	learn: 0.1161997	total: 3.53s	remaining: 4m 39s
15:	learn: 0.1137206	total: 3.73s	remaining: 4m 36s
16:	learn: 0.1113362	total: 3.98s	remaining: 4m 37s
17:	learn: 0.1090303	total: 4.13s	remaining: 4m 31s
18:	learn: 0.1068153	total: 4.31s	remaining: 4m 28s
19:	learn: 0.1046854	total: 4.51s	remaining: 4m 26s
20:	learn: 0.1026321	total: 4.7s	remaining: 4m 24s
21:	learn: 0.1006638	total: 4.92s	remaining: 4m 23s
22:	learn: 0.0987691	total: 5.14s	remaining: 4m 23s
23:	learn: 0.0969514	total: 5.31s	remaining: 4m 20s
24:	learn: 0.0951794	total: 5.49s	remaining: 4m 17s
25:	learn: 0.0934951	total: 5.61s	remaining: 4m 13s
26:	learn: 0.0918633	total: 5.8s	remaining: 4m 11s
27:	learn: 0.0902977	total: 6.01s	remaining: 4m 11s
28:	learn: 0.0887502	total: 6.21s	remaining: 4m 10s
29:	learn: 0.0872679	total: 6.41s	remaining: 4m 9s
30:	learn: 0.0858515	total: 6.53s	remaining: 4m 6s
31:	learn: 0.0844943	total: 6.66s	remaining: 4m 3s
32:	learn: 0.0831972	total: 6.81s	remaining: 4m
33:	learn: 0.0819621	total: 6.98s	remaining: 3m 59s
34:	learn: 0.0807741	total: 7.18s	remaining: 3m 58s
35:	learn: 0.0796404	total: 7.36s	remaining: 3m 57s
36:	learn: 0.0785583	total: 7.58s	remaining: 3m 58s
37:	learn: 0.0775184	total: 7.77s	remaining: 3m 57s
38:	learn: 0.0765273	total: 8s	remaining: 3m 58s
39:	learn: 0.0755797	total: 8.2s	remaining: 3m 57s
40:	learn: 0.0746775	total: 8.39s	remaining: 3m 57s
41:	learn: 0.0738123	total: 8.6s	remaining: 3m 57s
42:	learn: 0.0729890	total: 8.81s	remaining: 3m 57s
43:	learn: 0.0722023	total: 9.01s	remaining: 3m 56s
44:	learn: 0.0714495	total: 9.2s	remaining: 3m 56s
45:	learn: 0.0707274	total: 9.43s	remaining: 3m 56s
46:	learn: 0.0700450	total: 9.65s	remaining: 3m 56s
47:	learn: 0.0693957	total: 9.85s	remaining: 3m 56s
48:	learn: 0.0687762	total: 9.99s	remaining: 3m 54s
49:	learn: 0.0681915	total: 10.2s	remaining: 3m 55s
50:	learn: 0.0676273	total: 10.4s	remaining: 3m 54s
51:	learn: 0.0670845	total: 10.6s	remaining: 3m 52s
52:	learn: 0.0665787	total: 10.7s	remaining: 3m 52s
53:	learn: 0.0660894	total: 10.9s	remaining: 3m 51s
54:	learn: 0.0656267	total: 11.1s	remaining: 3m 51s
55:	learn: 0.0651856	total: 11.3s	remaining: 3m 50s
56:	learn: 0.0647675	total: 11.5s	remaining: 3m 49s
57:	learn: 0.0643654	total: 11.7s	remaining: 3m 50s
58:	learn: 0.0639878	total: 12s	remaining: 3m 51s
59:	learn: 0.0636267	total: 12.2s	remaining: 3m 50s
60:	learn: 0.0632866	total: 12.4s	remaining: 3m 51s
61:	learn: 0.0629602	total: 12.6s	remaining: 3m 50s
62:	learn: 0.0626562	total: 12.8s	remaining: 3m 50s
63:	learn: 0.0623610	total: 13s	remaining: 3m 50s
64:	learn: 0.0620805	total: 13.2s	remaining: 3m 51s
65:	learn: 0.0618165	total: 13.5s	remaining: 3m 51s
66:	learn: 0.0615645	total: 13.7s	remaining: 3m 51s
67:	learn: 0.0613255	total: 14s	remaining: 3m 52s
68:	learn: 0.0611009	total: 14.2s	remaining: 3m 52s
69:	learn: 0.0608883	total: 14.5s	remaining: 3m 53s
70:	learn: 0.0606869	total: 14.8s	remaining: 3m 54s
71:	learn: 0.0604916	total: 15s	remaining: 3m 54s
72:	learn: 0.0603065	total: 15.2s	remaining: 3m 54s
73:	learn: 0.0601317	total: 15.4s	remaining: 3m 54s
74:	learn: 0.0599657	total: 15.7s	remaining: 3m 55s
75:	learn: 0.0598110	total: 15.9s	remaining: 3m 55s
76:	learn: 0.0596612	total: 16.1s	remaining: 3m 55s
77:	learn: 0.0595198	total: 16.4s	remaining: 3m 55s
78:	learn: 0.0593860	total: 16.6s	remaining: 3m 56s
79:	learn: 0.0592596	total: 16.9s	remaining: 3m 56s
80:	learn: 0.0591396	total: 17.2s	remaining: 3m 57s
81:	learn: 0.0590240	total: 17.4s	remaining: 3m 57s
82:	learn: 0.0589142	total: 17.6s	remaining: 3m 56s
83:	learn: 0.0588100	total: 17.8s	remaining: 3m 56s
84:	learn: 0.0587129	total: 18s	remaining: 3m 55s
85:	learn: 0.0586209	total: 18.3s	remaining: 3m 56s
86:	learn: 0.0585336	total: 18.5s	remaining: 3m 56s
87:	learn: 0.0584511	total: 18.7s	remaining: 3m 56s
88:	learn: 0.0583710	total: 18.9s	remaining: 3m 56s
89:	learn: 0.0582949	total: 19.1s	remaining: 3m 55s
90:	learn: 0.0582248	total: 19.3s	remaining: 3m 55s
91:	learn: 0.0581585	total: 19.6s	remaining: 3m 56s
92:	learn: 0.0580958	total: 19.8s	remaining: 3m 55s
93:	learn: 0.0580342	total: 20s	remaining: 3m 55s
94:	learn: 0.0579758	total: 20.3s	remaining: 3m 55s
95:	learn: 0.0579221	total: 20.5s	remaining: 3m 56s
96:	learn: 0.0578709	total: 20.8s	remaining: 3m 56s
97:	learn: 0.0578214	total: 21.1s	remaining: 3m 57s
98:	learn: 0.0577751	total: 21.3s	remaining: 3m 57s
99:	learn: 0.0577295	total: 21.6s	remaining: 3m 57s
100:	learn: 0.0576870	total: 21.7s	remaining: 3m 56s
101:	learn: 0.0576473	total: 22s	remaining: 3m 56s
102:	learn: 0.0576086	total: 22.2s	remaining: 3m 56s
103:	learn: 0.0575721	total: 22.4s	remaining: 3m 56s
104:	learn: 0.0575371	total: 22.6s	remaining: 3m 55s
105:	learn: 0.0575043	total: 22.8s	remaining: 3m 55s
106:	learn: 0.0574737	total: 23.1s	remaining: 3m 55s
107:	learn: 0.0574438	total: 23.4s	remaining: 3m 56s
108:	learn: 0.0574155	total: 23.6s	remaining: 3m 56s
109:	learn: 0.0573890	total: 23.8s	remaining: 3m 55s
110:	learn: 0.0573623	total: 24s	remaining: 3m 55s
111:	learn: 0.0573369	total: 24.2s	remaining: 3m 55s
112:	learn: 0.0573138	total: 24.5s	remaining: 3m 55s
113:	learn: 0.0572902	total: 24.7s	remaining: 3m 55s
114:	learn: 0.0572687	total: 25s	remaining: 3m 56s
115:	learn: 0.0572485	total: 25.3s	remaining: 3m 56s
116:	learn: 0.0572295	total: 25.6s	remaining: 3m 56s
117:	learn: 0.0572111	total: 25.8s	remaining: 3m 56s
118:	learn: 0.0571920	total: 26.1s	remaining: 3m 56s
119:	learn: 0.0571736	total: 26.3s	remaining: 3m 56s
120:	learn: 0.0571548	total: 26.5s	remaining: 3m 56s
121:	learn: 0.0571391	total: 26.8s	remaining: 3m 56s
122:	learn: 0.0571236	total: 27s	remaining: 3m 56s
123:	learn: 0.0571084	total: 27.2s	remaining: 3m 56s
124:	learn: 0.0570939	total: 27.5s	remaining: 3m 56s
125:	learn: 0.0570799	total: 27.7s	remaining: 3m 56s
126:	learn: 0.0570659	total: 27.9s	remaining: 3m 56s
127:	learn: 0.0570537	total: 28.1s	remaining: 3m 55s
128:	learn: 0.0570419	total: 28.4s	remaining: 3m 55s
129:	learn: 0.0570293	total: 28.6s	remaining: 3m 55s
130:	learn: 0.0570174	total: 28.8s	remaining: 3m 54s
131:	learn: 0.0570066	total: 29s	remaining: 3m 54s
132:	learn: 0.0569949	total: 29.3s	remaining: 3m 54s
133:	learn: 0.0569833	total: 29.5s	remaining: 3m 54s
134:	learn: 0.0569733	total: 29.8s	remaining: 3m 54s
135:	learn: 0.0569643	total: 30.1s	remaining: 3m 55s
136:	learn: 0.0569552	total: 30.3s	remaining: 3m 55s
137:	learn: 0.0569451	total: 30.5s	remaining: 3m 54s
138:	learn: 0.0569366	total: 30.8s	remaining: 3m 55s
139:	learn: 0.0569278	total: 31s	remaining: 3m 55s
140:	learn: 0.0569185	total: 31.3s	remaining: 3m 54s
141:	learn: 0.0569105	total: 31.5s	remaining: 3m 54s
142:	learn: 0.0569015	total: 31.7s	remaining: 3m 54s
143:	learn: 0.0568944	total: 32s	remaining: 3m 54s
144:	learn: 0.0568871	total: 32.2s	remaining: 3m 54s
145:	learn: 0.0568792	total: 32.4s	remaining: 3m 53s
146:	learn: 0.0568705	total: 32.6s	remaining: 3m 53s
147:	learn: 0.0568646	total: 32.9s	remaining: 3m 53s
148:	learn: 0.0568572	total: 33.1s	remaining: 3m 53s
149:	learn: 0.0568509	total: 33.3s	remaining: 3m 53s
150:	learn: 0.0568446	total: 33.6s	remaining: 3m 53s
151:	learn: 0.0568387	total: 33.8s	remaining: 3m 53s
152:	learn: 0.0568335	total: 34.1s	remaining: 3m 53s
153:	learn: 0.0568256	total: 34.3s	remaining: 3m 53s
154:	learn: 0.0568183	total: 34.6s	remaining: 3m 53s
155:	learn: 0.0568135	total: 34.8s	remaining: 3m 52s
156:	learn: 0.0568081	total: 35s	remaining: 3m 52s
157:	learn: 0.0568036	total: 35.3s	remaining: 3m 52s
0:	learn: 0.1621165	total: 321ms	remaining: 6m 25s
1:	learn: 0.1580225	total: 532ms	remaining: 5m 18s
2:	learn: 0.1540724	total: 802ms	remaining: 5m 20s
3:	learn: 0.1502591	total: 1s	remaining: 4m 59s
4:	learn: 0.1465755	total: 1.22s	remaining: 4m 51s
5:	learn: 0.1430164	total: 1.48s	remaining: 4m 54s
6:	learn: 0.1395858	total: 1.67s	remaining: 4m 45s
7:	learn: 0.1362524	total: 1.91s	remaining: 4m 43s
8:	learn: 0.1330520	total: 2.13s	remaining: 4m 42s
9:	learn: 0.1299498	total: 2.31s	remaining: 4m 34s
10:	learn: 0.1269767	total: 2.52s	remaining: 4m 32s
11:	learn: 0.1241088	total: 2.75s	remaining: 4m 32s
12:	learn: 0.1213366	total: 2.96s	remaining: 4m 30s
13:	learn: 0.1186540	total: 3.15s	remaining: 4m 27s
14:	learn: 0.1160747	total: 3.42s	remaining: 4m 29s
15:	learn: 0.1135918	total: 3.58s	remaining: 4m 25s
16:	learn: 0.1112082	total: 3.8s	remaining: 4m 24s
17:	learn: 0.1089101	total: 3.96s	remaining: 4m 19s
18:	learn: 0.1066992	total: 4.16s	remaining: 4m 18s
19:	learn: 0.1045731	total: 4.38s	remaining: 4m 18s
20:	learn: 0.1025149	total: 4.59s	remaining: 4m 17s
21:	learn: 0.1005447	total: 4.8s	remaining: 4m 17s
22:	learn: 0.0986535	total: 4.99s	remaining: 4m 15s
23:	learn: 0.0968082	total: 5.25s	remaining: 4m 17s
24:	learn: 0.0950565	total: 5.47s	remaining: 4m 17s
25:	learn: 0.0933723	total: 5.72s	remaining: 4m 18s
26:	learn: 0.0917209	total: 5.94s	remaining: 4m 18s
27:	learn: 0.0901529	total: 6.15s	remaining: 4m 17s
28:	learn: 0.0886065	total: 6.37s	remaining: 4m 17s
29:	learn: 0.0871641	total: 6.57s	remaining: 4m 16s
30:	learn: 0.0857440	total: 6.82s	remaining: 4m 17s
31:	learn: 0.0843838	total: 7.09s	remaining: 4m 18s
32:	learn: 0.0830837	total: 7.39s	remaining: 4m 21s
33:	learn: 0.0818511	total: 7.59s	remaining: 4m 20s
34:	learn: 0.0806718	total: 7.86s	remaining: 4m 21s
35:	learn: 0.0795314	total: 8.05s	remaining: 4m 20s
36:	learn: 0.0784418	total: 8.27s	remaining: 4m 20s
37:	learn: 0.0774033	total: 8.49s	remaining: 4m 19s
38:	learn: 0.0764172	total: 8.66s	remaining: 4m 17s
39:	learn: 0.0754674	total: 8.81s	remaining: 4m 15s
40:	learn: 0.0745602	total: 9.03s	remaining: 4m 15s
41:	learn: 0.0736946	total: 9.21s	remaining: 4m 13s
42:	learn: 0.0728688	total: 9.42s	remaining: 4m 13s
43:	learn: 0.0720746	total: 9.62s	remaining: 4m 12s
44:	learn: 0.0713209	total: 9.82s	remaining: 4m 12s
45:	learn: 0.0705987	total: 10s	remaining: 4m 11s
46:	learn: 0.0699122	total: 10.2s	remaining: 4m 11s
47:	learn: 0.0692587	total: 10.4s	remaining: 4m 10s
48:	learn: 0.0686357	total: 10.6s	remaining: 4m 8s
49:	learn: 0.0680416	total: 10.8s	remaining: 4m 7s
50:	learn: 0.0674789	total: 10.9s	remaining: 4m 6s
51:	learn: 0.0669349	total: 11.2s	remaining: 4m 6s
52:	learn: 0.0664241	total: 11.4s	remaining: 4m 7s
53:	learn: 0.0659338	total: 11.7s	remaining: 4m 7s
54:	learn: 0.0654696	total: 11.9s	remaining: 4m 8s
55:	learn: 0.0650293	total: 12.1s	remaining: 4m 6s
56:	learn: 0.0646186	total: 12.3s	remaining: 4m 6s
57:	learn: 0.0642181	total: 12.5s	remaining: 4m 6s
58:	learn: 0.0638392	total: 12.8s	remaining: 4m 6s
59:	learn: 0.0634769	total: 13s	remaining: 4m 7s
60:	learn: 0.0631375	total: 13.3s	remaining: 4m 7s
61:	learn: 0.0628115	total: 13.5s	remaining: 4m 7s
62:	learn: 0.0625025	total: 13.7s	remaining: 4m 6s
63:	learn: 0.0622088	total: 13.9s	remaining: 4m 6s
64:	learn: 0.0619302	total: 14.1s	remaining: 4m 6s
65:	learn: 0.0616656	total: 14.4s	remaining: 4m 7s
66:	learn: 0.0614138	total: 14.7s	remaining: 4m 8s
67:	learn: 0.0611744	total: 15s	remaining: 4m 9s
68:	learn: 0.0609490	total: 15.2s	remaining: 4m 8s

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning:
160 fits failed out of a total of 250.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
90 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/catboost/core.py", line 5873, in fit
    return self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/catboost/core.py", line 2395, in _fit
    train_params = self._prepare_train_params(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/catboost/core.py", line 2321, in _prepare_train_params
    _check_train_params(params)
  File "_catboost.pyx", line 6601, in _catboost._check_train_params
  File "_catboost.pyx", line 6623, in _catboost._check_train_params
_catboost.CatBoostError: catboost/private/libs/options/bootstrap_options.cpp:16: Error: bayesian bootstrap doesn't support 'subsample' option

--------------------------------------------------------------------------------
70 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/catboost/core.py", line 5873, in fit
    return self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/catboost/core.py", line 2395, in _fit
    train_params = self._prepare_train_params(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/catboost/core.py", line 2321, in _prepare_train_params
    _check_train_params(params)
  File "_catboost.pyx", line 6601, in _catboost._check_train_params
  File "_catboost.pyx", line 6623, in _catboost._check_train_params
_catboost.CatBoostError: catboost/private/libs/options/bootstrap_options.cpp:44: Error: bagging temperature available for bayesian bootstrap only

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:952: UserWarning: One or more of the test scores are non-finite: [        nan -0.00315389 -0.00322683         nan -0.0045738  -0.0032845
         nan -0.00317299 -0.00317322         nan         nan -0.00315292
         nan         nan         nan -0.00319733         nan         nan
         nan -0.00315049 -0.00315382         nan -0.00315371         nan
 -0.00318319         nan         nan         nan         nan -0.0031664
         nan         nan -0.0031685          nan         nan         nan
         nan         nan         nan -0.00329377         nan -0.00323687
         nan -0.00314425         nan         nan         nan         nan
         nan -0.00318436]
  warnings.warn(

0:	learn: 0.1527704	total: 58.4ms	remaining: 46.6s
1:	learn: 0.1403452	total: 108ms	remaining: 43s
2:	learn: 0.1301250	total: 144ms	remaining: 38.2s
3:	learn: 0.1199464	total: 190ms	remaining: 37.7s
4:	learn: 0.1110023	total: 234ms	remaining: 37.2s
5:	learn: 0.1031657	total: 281ms	remaining: 37.1s
6:	learn: 0.0963513	total: 325ms	remaining: 36.8s
7:	learn: 0.0904094	total: 371ms	remaining: 36.7s
8:	learn: 0.0852463	total: 414ms	remaining: 36.4s
9:	learn: 0.0809817	total: 460ms	remaining: 36.4s
10:	learn: 0.0771621	total: 506ms	remaining: 36.3s
11:	learn: 0.0740856	total: 546ms	remaining: 35.8s
12:	learn: 0.0712931	total: 590ms	remaining: 35.7s
13:	learn: 0.0688955	total: 634ms	remaining: 35.6s
14:	learn: 0.0670191	total: 677ms	remaining: 35.4s
15:	learn: 0.0653781	total: 725ms	remaining: 35.5s
16:	learn: 0.0640405	total: 771ms	remaining: 35.5s
17:	learn: 0.0628329	total: 813ms	remaining: 35.3s
18:	learn: 0.0619281	total: 855ms	remaining: 35.1s
19:	learn: 0.0610427	total: 898ms	remaining: 35s
20:	learn: 0.0603279	total: 944ms	remaining: 35s
21:	learn: 0.0597763	total: 987ms	remaining: 34.9s
22:	learn: 0.0592800	total: 1.03s	remaining: 34.7s
23:	learn: 0.0588772	total: 1.07s	remaining: 34.6s
24:	learn: 0.0585814	total: 1.11s	remaining: 34.6s
25:	learn: 0.0583206	total: 1.16s	remaining: 34.5s
26:	learn: 0.0580720	total: 1.2s	remaining: 34.4s
27:	learn: 0.0578765	total: 1.25s	remaining: 34.4s
28:	learn: 0.0577227	total: 1.29s	remaining: 34.3s
29:	learn: 0.0575808	total: 1.33s	remaining: 34.3s
30:	learn: 0.0574436	total: 1.38s	remaining: 34.2s
31:	learn: 0.0573368	total: 1.43s	remaining: 34.3s
32:	learn: 0.0572249	total: 1.48s	remaining: 34.3s
33:	learn: 0.0571345	total: 1.52s	remaining: 34.2s
34:	learn: 0.0570930	total: 1.56s	remaining: 34.1s
35:	learn: 0.0570400	total: 1.61s	remaining: 34.1s
36:	learn: 0.0569984	total: 1.65s	remaining: 34.1s
37:	learn: 0.0569839	total: 1.68s	remaining: 33.7s
38:	learn: 0.0569491	total: 1.73s	remaining: 33.7s
39:	learn: 0.0569121	total: 1.76s	remaining: 33.5s
40:	learn: 0.0568781	total: 1.81s	remaining: 33.5s
41:	learn: 0.0568423	total: 1.85s	remaining: 33.5s
42:	learn: 0.0568144	total: 1.9s	remaining: 33.5s
43:	learn: 0.0567926	total: 1.95s	remaining: 33.5s
44:	learn: 0.0567719	total: 1.99s	remaining: 33.4s
45:	learn: 0.0567558	total: 2.04s	remaining: 33.4s
46:	learn: 0.0567397	total: 2.08s	remaining: 33.3s
47:	learn: 0.0567247	total: 2.12s	remaining: 33.2s
48:	learn: 0.0567165	total: 2.17s	remaining: 33.2s
49:	learn: 0.0567035	total: 2.21s	remaining: 33.2s
50:	learn: 0.0566911	total: 2.26s	remaining: 33.2s
51:	learn: 0.0566898	total: 2.28s	remaining: 32.8s
52:	learn: 0.0566802	total: 2.33s	remaining: 32.8s
53:	learn: 0.0566725	total: 2.37s	remaining: 32.8s
54:	learn: 0.0566711	total: 2.4s	remaining: 32.5s
55:	learn: 0.0566564	total: 2.45s	remaining: 32.6s
56:	learn: 0.0566412	total: 2.49s	remaining: 32.5s
57:	learn: 0.0566345	total: 2.53s	remaining: 32.4s
58:	learn: 0.0566230	total: 2.58s	remaining: 32.4s
59:	learn: 0.0566187	total: 2.62s	remaining: 32.3s
60:	learn: 0.0566062	total: 2.67s	remaining: 32.3s
61:	learn: 0.0566015	total: 2.71s	remaining: 32.3s
62:	learn: 0.0565972	total: 2.75s	remaining: 32.2s
63:	learn: 0.0565933	total: 2.8s	remaining: 32.2s
64:	learn: 0.0565885	total: 2.85s	remaining: 32.2s
65:	learn: 0.0565857	total: 2.9s	remaining: 32.2s
66:	learn: 0.0565816	total: 2.95s	remaining: 32.3s
67:	learn: 0.0565793	total: 3s	remaining: 32.3s
68:	learn: 0.0565696	total: 3.04s	remaining: 32.3s
69:	learn: 0.0565606	total: 3.09s	remaining: 32.2s
70:	learn: 0.0565577	total: 3.14s	remaining: 32.2s
71:	learn: 0.0565494	total: 3.19s	remaining: 32.2s
72:	learn: 0.0565448	total: 3.23s	remaining: 32.2s
73:	learn: 0.0565422	total: 3.27s	remaining: 32.1s
74:	learn: 0.0565396	total: 3.32s	remaining: 32.1s
75:	learn: 0.0565373	total: 3.37s	remaining: 32.1s
76:	learn: 0.0565359	total: 3.4s	remaining: 32s
77:	learn: 0.0565307	total: 3.45s	remaining: 32s
78:	learn: 0.0565284	total: 3.5s	remaining: 32s
79:	learn: 0.0565195	total: 3.55s	remaining: 31.9s
80:	learn: 0.0565187	total: 3.59s	remaining: 31.9s
81:	learn: 0.0565157	total: 3.63s	remaining: 31.8s
82:	learn: 0.0565084	total: 3.69s	remaining: 31.8s
83:	learn: 0.0565049	total: 3.74s	remaining: 31.9s
84:	learn: 0.0565032	total: 3.79s	remaining: 31.9s
85:	learn: 0.0565032	total: 3.83s	remaining: 31.8s
86:	learn: 0.0565002	total: 3.88s	remaining: 31.8s
87:	learn: 0.0564997	total: 3.93s	remaining: 31.8s
88:	learn: 0.0564997	total: 3.95s	remaining: 31.6s
89:	learn: 0.0564995	total: 3.98s	remaining: 31.4s
90:	learn: 0.0564953	total: 4.03s	remaining: 31.4s
91:	learn: 0.0564937	total: 4.08s	remaining: 31.4s
92:	learn: 0.0564913	total: 4.12s	remaining: 31.3s
93:	learn: 0.0564891	total: 4.17s	remaining: 31.3s
94:	learn: 0.0564880	total: 4.21s	remaining: 31.2s
95:	learn: 0.0564872	total: 4.25s	remaining: 31.2s
96:	learn: 0.0564857	total: 4.29s	remaining: 31.1s
97:	learn: 0.0564831	total: 4.34s	remaining: 31.1s
98:	learn: 0.0564808	total: 4.39s	remaining: 31.1s
99:	learn: 0.0564796	total: 4.43s	remaining: 31s
100:	learn: 0.0564792	total: 4.45s	remaining: 30.8s
101:	learn: 0.0564764	total: 4.5s	remaining: 30.8s
102:	learn: 0.0564763	total: 4.52s	remaining: 30.6s
103:	learn: 0.0564735	total: 4.57s	remaining: 30.6s
104:	learn: 0.0564631	total: 4.62s	remaining: 30.6s
105:	learn: 0.0564623	total: 4.65s	remaining: 30.5s
106:	learn: 0.0564610	total: 4.7s	remaining: 30.4s
107:	learn: 0.0564568	total: 4.74s	remaining: 30.3s
108:	learn: 0.0564538	total: 4.78s	remaining: 30.3s
109:	learn: 0.0564513	total: 4.83s	remaining: 30.3s
110:	learn: 0.0564489	total: 4.88s	remaining: 30.3s
111:	learn: 0.0564488	total: 4.91s	remaining: 30.1s
112:	learn: 0.0564468	total: 4.95s	remaining: 30.1s
113:	learn: 0.0564460	total: 5s	remaining: 30.1s
114:	learn: 0.0564443	total: 5.04s	remaining: 30s
115:	learn: 0.0564431	total: 5.08s	remaining: 30s
116:	learn: 0.0564389	total: 5.13s	remaining: 30s
117:	learn: 0.0564357	total: 5.18s	remaining: 29.9s
118:	learn: 0.0564337	total: 5.22s	remaining: 29.9s
119:	learn: 0.0564333	total: 5.27s	remaining: 29.9s
120:	learn: 0.0564315	total: 5.32s	remaining: 29.9s
121:	learn: 0.0564282	total: 5.36s	remaining: 29.8s
122:	learn: 0.0564253	total: 5.41s	remaining: 29.8s
123:	learn: 0.0564214	total: 5.45s	remaining: 29.7s
124:	learn: 0.0564174	total: 5.49s	remaining: 29.7s
125:	learn: 0.0564123	total: 5.54s	remaining: 29.6s
126:	learn: 0.0564108	total: 5.58s	remaining: 29.6s
127:	learn: 0.0564093	total: 5.61s	remaining: 29.5s
128:	learn: 0.0564080	total: 5.66s	remaining: 29.4s
129:	learn: 0.0564010	total: 5.7s	remaining: 29.4s
130:	learn: 0.0563949	total: 5.74s	remaining: 29.3s
131:	learn: 0.0563930	total: 5.78s	remaining: 29.3s
132:	learn: 0.0563873	total: 5.83s	remaining: 29.2s
133:	learn: 0.0563821	total: 5.88s	remaining: 29.2s
134:	learn: 0.0563790	total: 5.93s	remaining: 29.2s
135:	learn: 0.0563759	total: 5.98s	remaining: 29.2s
136:	learn: 0.0563735	total: 6.02s	remaining: 29.1s
137:	learn: 0.0563698	total: 6.07s	remaining: 29.1s
138:	learn: 0.0563695	total: 6.09s	remaining: 28.9s
139:	learn: 0.0563676	total: 6.13s	remaining: 28.9s
140:	learn: 0.0563643	total: 6.17s	remaining: 28.9s
141:	learn: 0.0563588	total: 6.22s	remaining: 28.8s
142:	learn: 0.0563533	total: 6.26s	remaining: 28.8s
143:	learn: 0.0563490	total: 6.3s	remaining: 28.7s
144:	learn: 0.0563445	total: 6.34s	remaining: 28.6s
145:	learn: 0.0563426	total: 6.38s	remaining: 28.6s
146:	learn: 0.0563384	total: 6.43s	remaining: 28.5s
147:	learn: 0.0563354	total: 6.48s	remaining: 28.5s
148:	learn: 0.0563320	total: 6.52s	remaining: 28.5s
149:	learn: 0.0563251	total: 6.57s	remaining: 28.5s
150:	learn: 0.0563191	total: 6.63s	remaining: 28.5s
151:	learn: 0.0563171	total: 6.7s	remaining: 28.5s
152:	learn: 0.0563135	total: 6.75s	remaining: 28.5s
153:	learn: 0.0563066	total: 6.79s	remaining: 28.5s
154:	learn: 0.0563023	total: 6.84s	remaining: 28.5s
155:	learn: 0.0562999	total: 6.88s	remaining: 28.4s
156:	learn: 0.0562935	total: 6.93s	remaining: 28.4s
157:	learn: 0.0562883	total: 6.97s	remaining: 28.3s
158:	learn: 0.0562852	total: 7.01s	remaining: 28.3s
159:	learn: 0.0562816	total: 7.05s	remaining: 28.2s
160:	learn: 0.0562779	total: 7.09s	remaining: 28.2s
161:	learn: 0.0562742	total: 7.13s	remaining: 28.1s
162:	learn: 0.0562707	total: 7.18s	remaining: 28s
163:	learn: 0.0562679	total: 7.22s	remaining: 28s
164:	learn: 0.0562633	total: 7.26s	remaining: 27.9s
165:	learn: 0.0562591	total: 7.3s	remaining: 27.9s
166:	learn: 0.0562538	total: 7.35s	remaining: 27.9s
167:	learn: 0.0562512	total: 7.39s	remaining: 27.8s
168:	learn: 0.0562486	total: 7.44s	remaining: 27.8s
169:	learn: 0.0562456	total: 7.48s	remaining: 27.7s
170:	learn: 0.0562429	total: 7.53s	remaining: 27.7s
171:	learn: 0.0562378	total: 7.57s	remaining: 27.6s
172:	learn: 0.0562359	total: 7.61s	remaining: 27.6s
173:	learn: 0.0562299	total: 7.66s	remaining: 27.6s
174:	learn: 0.0562271	total: 7.71s	remaining: 27.5s
175:	learn: 0.0562243	total: 7.75s	remaining: 27.5s
176:	learn: 0.0562195	total: 7.8s	remaining: 27.5s
177:	learn: 0.0562169	total: 7.85s	remaining: 27.4s
178:	learn: 0.0562142	total: 7.89s	remaining: 27.4s
179:	learn: 0.0562114	total: 7.94s	remaining: 27.3s
180:	learn: 0.0562101	total: 7.97s	remaining: 27.3s
181:	learn: 0.0562068	total: 8.02s	remaining: 27.2s
182:	learn: 0.0562047	total: 8.06s	remaining: 27.2s
183:	learn: 0.0562025	total: 8.11s	remaining: 27.1s
184:	learn: 0.0561985	total: 8.16s	remaining: 27.1s
185:	learn: 0.0561960	total: 8.2s	remaining: 27.1s
186:	learn: 0.0561929	total: 8.25s	remaining: 27.1s
187:	learn: 0.0561888	total: 8.3s	remaining: 27s
188:	learn: 0.0561865	total: 8.34s	remaining: 27s
189:	learn: 0.0561846	total: 8.39s	remaining: 26.9s
190:	learn: 0.0561809	total: 8.44s	remaining: 26.9s
191:	learn: 0.0561794	total: 8.48s	remaining: 26.9s
192:	learn: 0.0561777	total: 8.52s	remaining: 26.8s
193:	learn: 0.0561743	total: 8.57s	remaining: 26.8s
194:	learn: 0.0561718	total: 8.62s	remaining: 26.7s
195:	learn: 0.0561699	total: 8.66s	remaining: 26.7s
196:	learn: 0.0561681	total: 8.7s	remaining: 26.6s
197:	learn: 0.0561658	total: 8.75s	remaining: 26.6s
198:	learn: 0.0561639	total: 8.8s	remaining: 26.6s
199:	learn: 0.0561611	total: 8.84s	remaining: 26.5s
200:	learn: 0.0561580	total: 8.89s	remaining: 26.5s
201:	learn: 0.0561559	total: 8.94s	remaining: 26.5s
202:	learn: 0.0561479	total: 8.99s	remaining: 26.4s
203:	learn: 0.0561458	total: 9.03s	remaining: 26.4s
204:	learn: 0.0561435	total: 9.07s	remaining: 26.3s
205:	learn: 0.0561407	total: 9.12s	remaining: 26.3s
206:	learn: 0.0561392	total: 9.16s	remaining: 26.2s
207:	learn: 0.0561373	total: 9.21s	remaining: 26.2s
208:	learn: 0.0561350	total: 9.25s	remaining: 26.2s
209:	learn: 0.0561325	total: 9.29s	remaining: 26.1s
210:	learn: 0.0561305	total: 9.34s	remaining: 26.1s
211:	learn: 0.0561291	total: 9.38s	remaining: 26s
212:	learn: 0.0561274	total: 9.42s	remaining: 26s
213:	learn: 0.0561250	total: 9.46s	remaining: 25.9s
214:	learn: 0.0561232	total: 9.51s	remaining: 25.9s
215:	learn: 0.0561214	total: 9.55s	remaining: 25.8s
216:	learn: 0.0561199	total: 9.59s	remaining: 25.8s
217:	learn: 0.0561172	total: 9.63s	remaining: 25.7s
218:	learn: 0.0561136	total: 9.68s	remaining: 25.7s
219:	learn: 0.0561111	total: 9.72s	remaining: 25.6s
220:	learn: 0.0561093	total: 9.77s	remaining: 25.6s
221:	learn: 0.0561077	total: 9.82s	remaining: 25.6s
222:	learn: 0.0561039	total: 9.87s	remaining: 25.5s
223:	learn: 0.0561006	total: 9.92s	remaining: 25.5s
224:	learn: 0.0560994	total: 9.96s	remaining: 25.5s
225:	learn: 0.0560981	total: 10s	remaining: 25.4s
226:	learn: 0.0560968	total: 10s	remaining: 25.4s
227:	learn: 0.0560951	total: 10.1s	remaining: 25.3s
228:	learn: 0.0560927	total: 10.1s	remaining: 25.3s
229:	learn: 0.0560914	total: 10.2s	remaining: 25.2s
230:	learn: 0.0560896	total: 10.2s	remaining: 25.2s
231:	learn: 0.0560881	total: 10.3s	remaining: 25.1s
232:	learn: 0.0560864	total: 10.3s	remaining: 25.1s
233:	learn: 0.0560843	total: 10.4s	remaining: 25s
234:	learn: 0.0560815	total: 10.4s	remaining: 25s
235:	learn: 0.0560799	total: 10.4s	remaining: 25s
236:	learn: 0.0560776	total: 10.5s	remaining: 24.9s
237:	learn: 0.0560757	total: 10.5s	remaining: 24.9s
238:	learn: 0.0560721	total: 10.6s	remaining: 24.8s
239:	learn: 0.0560674	total: 10.6s	remaining: 24.8s
240:	learn: 0.0560658	total: 10.7s	remaining: 24.8s
241:	learn: 0.0560636	total: 10.7s	remaining: 24.7s
242:	learn: 0.0560612	total: 10.8s	remaining: 24.7s
243:	learn: 0.0560601	total: 10.8s	remaining: 24.6s
244:	learn: 0.0560587	total: 10.9s	remaining: 24.6s
245:	learn: 0.0560570	total: 10.9s	remaining: 24.5s
246:	learn: 0.0560546	total: 10.9s	remaining: 24.5s
247:	learn: 0.0560517	total: 11s	remaining: 24.5s
248:	learn: 0.0560486	total: 11s	remaining: 24.4s
249:	learn: 0.0560469	total: 11.1s	remaining: 24.4s
250:	learn: 0.0560452	total: 11.1s	remaining: 24.3s
251:	learn: 0.0560436	total: 11.2s	remaining: 24.3s
252:	learn: 0.0560395	total: 11.2s	remaining: 24.3s
253:	learn: 0.0560365	total: 11.3s	remaining: 24.2s
254:	learn: 0.0560353	total: 11.3s	remaining: 24.2s
255:	learn: 0.0560342	total: 11.4s	remaining: 24.1s
256:	learn: 0.0560330	total: 11.4s	remaining: 24.1s
257:	learn: 0.0560311	total: 11.5s	remaining: 24.1s
258:	learn: 0.0560290	total: 11.5s	remaining: 24.1s
259:	learn: 0.0560266	total: 11.6s	remaining: 24s
260:	learn: 0.0560254	total: 11.6s	remaining: 24s
261:	learn: 0.0560239	total: 11.6s	remaining: 23.9s
262:	learn: 0.0560227	total: 11.7s	remaining: 23.9s
263:	learn: 0.0560206	total: 11.7s	remaining: 23.8s
264:	learn: 0.0560181	total: 11.8s	remaining: 23.8s
265:	learn: 0.0560147	total: 11.8s	remaining: 23.7s
266:	learn: 0.0560110	total: 11.9s	remaining: 23.7s
267:	learn: 0.0560096	total: 11.9s	remaining: 23.7s
268:	learn: 0.0560071	total: 12s	remaining: 23.6s
269:	learn: 0.0560062	total: 12s	remaining: 23.6s
270:	learn: 0.0560045	total: 12s	remaining: 23.5s
271:	learn: 0.0560023	total: 12.1s	remaining: 23.5s
272:	learn: 0.0560005	total: 12.1s	remaining: 23.4s
273:	learn: 0.0559996	total: 12.2s	remaining: 23.4s
274:	learn: 0.0559972	total: 12.2s	remaining: 23.3s
275:	learn: 0.0559954	total: 12.3s	remaining: 23.3s
276:	learn: 0.0559915	total: 12.3s	remaining: 23.3s
277:	learn: 0.0559900	total: 12.4s	remaining: 23.2s
278:	learn: 0.0559884	total: 12.4s	remaining: 23.2s
279:	learn: 0.0559854	total: 12.4s	remaining: 23.1s
280:	learn: 0.0559838	total: 12.5s	remaining: 23.1s
281:	learn: 0.0559825	total: 12.5s	remaining: 23s
282:	learn: 0.0559804	total: 12.6s	remaining: 23s
283:	learn: 0.0559784	total: 12.6s	remaining: 22.9s
284:	learn: 0.0559775	total: 12.7s	remaining: 22.9s
285:	learn: 0.0559759	total: 12.7s	remaining: 22.9s
286:	learn: 0.0559747	total: 12.8s	remaining: 22.8s
287:	learn: 0.0559728	total: 12.8s	remaining: 22.8s
288:	learn: 0.0559706	total: 12.8s	remaining: 22.7s
289:	learn: 0.0559691	total: 12.9s	remaining: 22.7s
290:	learn: 0.0559675	total: 12.9s	remaining: 22.6s
291:	learn: 0.0559654	total: 13s	remaining: 22.6s
292:	learn: 0.0559645	total: 13s	remaining: 22.5s
293:	learn: 0.0559623	total: 13.1s	remaining: 22.5s
294:	learn: 0.0559604	total: 13.1s	remaining: 22.4s
295:	learn: 0.0559583	total: 13.2s	remaining: 22.4s
296:	learn: 0.0559566	total: 13.2s	remaining: 22.4s
297:	learn: 0.0559541	total: 13.3s	remaining: 22.3s
298:	learn: 0.0559529	total: 13.3s	remaining: 22.3s
299:	learn: 0.0559522	total: 13.3s	remaining: 22.2s
300:	learn: 0.0559509	total: 13.4s	remaining: 22.2s
301:	learn: 0.0559498	total: 13.4s	remaining: 22.1s
302:	learn: 0.0559473	total: 13.5s	remaining: 22.1s
303:	learn: 0.0559461	total: 13.5s	remaining: 22.1s
304:	learn: 0.0559442	total: 13.6s	remaining: 22s
305:	learn: 0.0559434	total: 13.6s	remaining: 22s
306:	learn: 0.0559417	total: 13.7s	remaining: 21.9s
307:	learn: 0.0559407	total: 13.7s	remaining: 21.9s
308:	learn: 0.0559400	total: 13.7s	remaining: 21.8s
309:	learn: 0.0559394	total: 13.8s	remaining: 21.8s
310:	learn: 0.0559371	total: 13.8s	remaining: 21.7s
311:	learn: 0.0559350	total: 13.9s	remaining: 21.7s
312:	learn: 0.0559332	total: 13.9s	remaining: 21.7s
313:	learn: 0.0559319	total: 14s	remaining: 21.6s
314:	learn: 0.0559304	total: 14s	remaining: 21.6s
315:	learn: 0.0559292	total: 14.1s	remaining: 21.5s
316:	learn: 0.0559277	total: 14.1s	remaining: 21.5s
317:	learn: 0.0559251	total: 14.2s	remaining: 21.5s
318:	learn: 0.0559232	total: 14.2s	remaining: 21.4s
319:	learn: 0.0559227	total: 14.2s	remaining: 21.4s
320:	learn: 0.0559210	total: 14.3s	remaining: 21.3s
321:	learn: 0.0559196	total: 14.3s	remaining: 21.3s
322:	learn: 0.0559179	total: 14.4s	remaining: 21.2s
323:	learn: 0.0559152	total: 14.4s	remaining: 21.2s
324:	learn: 0.0559145	total: 14.5s	remaining: 21.1s
325:	learn: 0.0559126	total: 14.5s	remaining: 21.1s
326:	learn: 0.0559112	total: 14.5s	remaining: 21s
327:	learn: 0.0559098	total: 14.6s	remaining: 21s
328:	learn: 0.0559084	total: 14.6s	remaining: 21s
329:	learn: 0.0559078	total: 14.7s	remaining: 20.9s
330:	learn: 0.0559071	total: 14.7s	remaining: 20.9s
331:	learn: 0.0559061	total: 14.8s	remaining: 20.8s
332:	learn: 0.0559053	total: 14.8s	remaining: 20.8s
333:	learn: 0.0559032	total: 14.8s	remaining: 20.7s
334:	learn: 0.0559021	total: 14.9s	remaining: 20.7s
335:	learn: 0.0559013	total: 14.9s	remaining: 20.6s
336:	learn: 0.0559001	total: 15s	remaining: 20.6s
337:	learn: 0.0558973	total: 15s	remaining: 20.5s
338:	learn: 0.0558960	total: 15.1s	remaining: 20.5s
339:	learn: 0.0558948	total: 15.1s	remaining: 20.4s
340:	learn: 0.0558929	total: 15.1s	remaining: 20.4s
341:	learn: 0.0558907	total: 15.2s	remaining: 20.3s
342:	learn: 0.0558896	total: 15.2s	remaining: 20.3s
343:	learn: 0.0558880	total: 15.3s	remaining: 20.2s
344:	learn: 0.0558868	total: 15.3s	remaining: 20.2s
345:	learn: 0.0558839	total: 15.4s	remaining: 20.2s
346:	learn: 0.0558829	total: 15.4s	remaining: 20.1s
347:	learn: 0.0558821	total: 15.5s	remaining: 20.1s
348:	learn: 0.0558799	total: 15.5s	remaining: 20s
349:	learn: 0.0558786	total: 15.5s	remaining: 20s
350:	learn: 0.0558775	total: 15.6s	remaining: 19.9s
351:	learn: 0.0558760	total: 15.6s	remaining: 19.9s
352:	learn: 0.0558745	total: 15.7s	remaining: 19.9s
353:	learn: 0.0558730	total: 15.7s	remaining: 19.8s
354:	learn: 0.0558711	total: 15.8s	remaining: 19.8s
355:	learn: 0.0558700	total: 15.8s	remaining: 19.7s
356:	learn: 0.0558684	total: 15.9s	remaining: 19.7s
357:	learn: 0.0558673	total: 15.9s	remaining: 19.6s
358:	learn: 0.0558660	total: 16s	remaining: 19.6s
359:	learn: 0.0558648	total: 16s	remaining: 19.6s
360:	learn: 0.0558641	total: 16s	remaining: 19.5s
361:	learn: 0.0558629	total: 16.1s	remaining: 19.5s
362:	learn: 0.0558617	total: 16.1s	remaining: 19.4s
363:	learn: 0.0558608	total: 16.2s	remaining: 19.4s
364:	learn: 0.0558597	total: 16.2s	remaining: 19.3s
365:	learn: 0.0558585	total: 16.3s	remaining: 19.3s
366:	learn: 0.0558571	total: 16.3s	remaining: 19.3s
367:	learn: 0.0558554	total: 16.4s	remaining: 19.2s
368:	learn: 0.0558540	total: 16.4s	remaining: 19.2s
369:	learn: 0.0558524	total: 16.5s	remaining: 19.1s
370:	learn: 0.0558510	total: 16.5s	remaining: 19.1s
371:	learn: 0.0558498	total: 16.6s	remaining: 19.1s
372:	learn: 0.0558483	total: 16.6s	remaining: 19s
373:	learn: 0.0558472	total: 16.7s	remaining: 19s
374:	learn: 0.0558461	total: 16.7s	remaining: 19s
375:	learn: 0.0558452	total: 16.8s	remaining: 18.9s
376:	learn: 0.0558442	total: 16.8s	remaining: 18.9s
377:	learn: 0.0558429	total: 16.9s	remaining: 18.8s
378:	learn: 0.0558412	total: 16.9s	remaining: 18.8s
379:	learn: 0.0558403	total: 17s	remaining: 18.8s
380:	learn: 0.0558397	total: 17s	remaining: 18.7s
381:	learn: 0.0558386	total: 17.1s	remaining: 18.7s
382:	learn: 0.0558375	total: 17.1s	remaining: 18.6s
383:	learn: 0.0558362	total: 17.1s	remaining: 18.6s
384:	learn: 0.0558349	total: 17.2s	remaining: 18.5s
385:	learn: 0.0558339	total: 17.2s	remaining: 18.5s
386:	learn: 0.0558330	total: 17.3s	remaining: 18.4s
387:	learn: 0.0558321	total: 17.3s	remaining: 18.4s
388:	learn: 0.0558307	total: 17.4s	remaining: 18.4s

In [16]:
print('best params:', gcv.best_params_)
print('best score:', gcv.best_score_)

best params: {'subsample': 1.0, 'random_strength': 5, 'min_data_in_leaf': 10, 'learning_rate': 0.1, 'leaf_estimation_iterations': 1, 'l2_leaf_reg': 5, 'iterations': 800, 'grow_policy': 'SymmetricTree', 'depth': 7, 'border_count': 128, 'bootstrap_type': 'MVS', 'bagging_temperature': 0.5}
best score: -0.003144248898098992
1571:	learn: 0.0563165	total: 6m 23s	remaining: 6.82s
1572:	learn: 0.0563162	total: 6m 23s	remaining: 6.58s
1573:	learn: 0.0563161	total: 6m 23s	remaining: 6.34s
1574:	learn: 0.0563158	total: 6m 23s	remaining: 6.09s
1575:	learn: 0.0563155	total: 6m 24s	remaining: 5.85s
1576:	learn: 0.0563153	total: 6m 24s	remaining: 5.61s
1577:	learn: 0.0563152	total: 6m 24s	remaining: 5.36s
1578:	learn: 0.0563150	total: 6m 24s	remaining: 5.12s
1579:	learn: 0.0563148	total: 6m 25s	remaining: 4.87s
1580:	learn: 0.0563146	total: 6m 25s	remaining: 4.63s
1581:	learn: 0.0563144	total: 6m 25s	remaining: 4.39s
1582:	learn: 0.0563142	total: 6m 25s	remaining: 4.14s
1583:	learn: 0.0563140	total: 6m 26s	remaining: 3.9s
1584:	learn: 0.0563138	total: 6m 26s	remaining: 3.65s
1585:	learn: 0.0563136	total: 6m 26s	remaining: 3.41s
1586:	learn: 0.0563134	total: 6m 26s	remaining: 3.17s
1587:	learn: 0.0563132	total: 6m 26s	remaining: 2.92s
1588:	learn: 0.0563131	total: 6m 27s	remaining: 2.68s
1589:	learn: 0.0563130	total: 6m 27s	remaining: 2.44s
1590:	learn: 0.0563127	total: 6m 27s	remaining: 2.19s
1591:	learn: 0.0563124	total: 6m 27s	remaining: 1.95s
1592:	learn: 0.0563122	total: 6m 27s	remaining: 1.7s
1593:	learn: 0.0563120	total: 6m 28s	remaining: 1.46s
1594:	learn: 0.0563118	total: 6m 28s	remaining: 1.22s
1595:	learn: 0.0563116	total: 6m 28s	remaining: 974ms
1596:	learn: 0.0563114	total: 6m 28s	remaining: 730ms
1597:	learn: 0.0563112	total: 6m 28s	remaining: 487ms
1598:	learn: 0.0563110	total: 6m 29s	remaining: 243ms
1599:	learn: 0.0563109	total: 6m 29s	remaining: 0us
1482:	learn: 0.0564720	total: 6m 4s	remaining: 28.8s
1483:	learn: 0.0564717	total: 6m 4s	remaining: 28.5s
1484:	learn: 0.0564714	total: 6m 5s	remaining: 28.3s
1485:	learn: 0.0564711	total: 6m 5s	remaining: 28s
1486:	learn: 0.0564709	total: 6m 5s	remaining: 27.8s
1487:	learn: 0.0564705	total: 6m 5s	remaining: 27.5s
1488:	learn: 0.0564703	total: 6m 6s	remaining: 27.3s
1489:	learn: 0.0564700	total: 6m 6s	remaining: 27s
1490:	learn: 0.0564697	total: 6m 6s	remaining: 26.8s
1491:	learn: 0.0564695	total: 6m 6s	remaining: 26.6s
1492:	learn: 0.0564693	total: 6m 7s	remaining: 26.3s
1493:	learn: 0.0564689	total: 6m 7s	remaining: 26.1s
1494:	learn: 0.0564687	total: 6m 7s	remaining: 25.8s
1495:	learn: 0.0564684	total: 6m 7s	remaining: 25.6s
1496:	learn: 0.0564683	total: 6m 7s	remaining: 25.3s
1497:	learn: 0.0564682	total: 6m 8s	remaining: 25.1s
1498:	learn: 0.0564678	total: 6m 8s	remaining: 24.8s
1499:	learn: 0.0564675	total: 6m 8s	remaining: 24.6s
1500:	learn: 0.0564673	total: 6m 8s	remaining: 24.3s
1501:	learn: 0.0564671	total: 6m 9s	remaining: 24.1s
1502:	learn: 0.0564668	total: 6m 9s	remaining: 23.8s
1503:	learn: 0.0564666	total: 6m 9s	remaining: 23.6s
1504:	learn: 0.0564664	total: 6m 9s	remaining: 23.4s
1505:	learn: 0.0564663	total: 6m 10s	remaining: 23.1s
1506:	learn: 0.0564661	total: 6m 10s	remaining: 22.9s
1507:	learn: 0.0564660	total: 6m 10s	remaining: 22.6s
1508:	learn: 0.0564658	total: 6m 10s	remaining: 22.4s
1509:	learn: 0.0564656	total: 6m 11s	remaining: 22.1s
1510:	learn: 0.0564653	total: 6m 11s	remaining: 21.9s
1511:	learn: 0.0564650	total: 6m 11s	remaining: 21.6s
1512:	learn: 0.0564648	total: 6m 11s	remaining: 21.4s
1513:	learn: 0.0564646	total: 6m 12s	remaining: 21.1s
1514:	learn: 0.0564645	total: 6m 12s	remaining: 20.9s
1515:	learn: 0.0564641	total: 6m 12s	remaining: 20.6s
1516:	learn: 0.0564640	total: 6m 12s	remaining: 20.4s
1517:	learn: 0.0564637	total: 6m 13s	remaining: 20.1s
1518:	learn: 0.0564636	total: 6m 13s	remaining: 19.9s
1519:	learn: 0.0564633	total: 6m 13s	remaining: 19.7s
1520:	learn: 0.0564631	total: 6m 13s	remaining: 19.4s
1521:	learn: 0.0564628	total: 6m 14s	remaining: 19.2s
1522:	learn: 0.0564625	total: 6m 14s	remaining: 18.9s
1523:	learn: 0.0564622	total: 6m 14s	remaining: 18.7s
1524:	learn: 0.0564619	total: 6m 14s	remaining: 18.4s
1525:	learn: 0.0564617	total: 6m 14s	remaining: 18.2s
1526:	learn: 0.0564616	total: 6m 15s	remaining: 17.9s
1527:	learn: 0.0564615	total: 6m 15s	remaining: 17.7s
1528:	learn: 0.0564613	total: 6m 15s	remaining: 17.4s
1529:	learn: 0.0564610	total: 6m 15s	remaining: 17.2s
1530:	learn: 0.0564608	total: 6m 16s	remaining: 17s
1531:	learn: 0.0564606	total: 6m 16s	remaining: 16.7s
1532:	learn: 0.0564603	total: 6m 16s	remaining: 16.5s
1533:	learn: 0.0564600	total: 6m 16s	remaining: 16.2s
1534:	learn: 0.0564596	total: 6m 17s	remaining: 16s
1535:	learn: 0.0564594	total: 6m 17s	remaining: 15.7s
1536:	learn: 0.0564591	total: 6m 17s	remaining: 15.5s
1537:	learn: 0.0564589	total: 6m 17s	remaining: 15.2s
1538:	learn: 0.0564587	total: 6m 18s	remaining: 15s
1539:	learn: 0.0564585	total: 6m 18s	remaining: 14.7s
1540:	learn: 0.0564582	total: 6m 18s	remaining: 14.5s
1541:	learn: 0.0564579	total: 6m 18s	remaining: 14.3s
1542:	learn: 0.0564577	total: 6m 19s	remaining: 14s
1543:	learn: 0.0564574	total: 6m 19s	remaining: 13.8s
1544:	learn: 0.0564572	total: 6m 19s	remaining: 13.5s
1545:	learn: 0.0564571	total: 6m 19s	remaining: 13.3s
1546:	learn: 0.0564569	total: 6m 20s	remaining: 13s
1547:	learn: 0.0564567	total: 6m 20s	remaining: 12.8s
1548:	learn: 0.0564566	total: 6m 20s	remaining: 12.5s
1549:	learn: 0.0564562	total: 6m 20s	remaining: 12.3s
1550:	learn: 0.0564560	total: 6m 21s	remaining: 12s
1551:	learn: 0.0564559	total: 6m 21s	remaining: 11.8s
1552:	learn: 0.0564557	total: 6m 21s	remaining: 11.5s
1553:	learn: 0.0564555	total: 6m 21s	remaining: 11.3s
1554:	learn: 0.0564553	total: 6m 22s	remaining: 11.1s
1555:	learn: 0.0564551	total: 6m 22s	remaining: 10.8s
1556:	learn: 0.0564550	total: 6m 22s	remaining: 10.6s
1557:	learn: 0.0564549	total: 6m 22s	remaining: 10.3s
1558:	learn: 0.0564546	total: 6m 23s	remaining: 10.1s
1559:	learn: 0.0564544	total: 6m 23s	remaining: 9.83s
1560:	learn: 0.0564543	total: 6m 23s	remaining: 9.58s
1561:	learn: 0.0564541	total: 6m 23s	remaining: 9.34s
1562:	learn: 0.0564540	total: 6m 23s	remaining: 9.09s
1563:	learn: 0.0564537	total: 6m 24s	remaining: 8.85s
1564:	learn: 0.0564536	total: 6m 24s	remaining: 8.6s
1565:	learn: 0.0564533	total: 6m 24s	remaining: 8.35s
1566:	learn: 0.0564531	total: 6m 25s	remaining: 8.11s
1567:	learn: 0.0564530	total: 6m 25s	remaining: 7.86s
1568:	learn: 0.0564528	total: 6m 25s	remaining: 7.62s
1569:	learn: 0.0564525	total: 6m 25s	remaining: 7.37s
1570:	learn: 0.0564523	total: 6m 25s	remaining: 7.13s
1571:	learn: 0.0564520	total: 6m 26s	remaining: 6.88s
1572:	learn: 0.0564517	total: 6m 26s	remaining: 6.63s
1573:	learn: 0.0564515	total: 6m 26s	remaining: 6.39s
1574:	learn: 0.0564513	total: 6m 27s	remaining: 6.14s
1575:	learn: 0.0564511	total: 6m 27s	remaining: 5.9s
1576:	learn: 0.0564509	total: 6m 27s	remaining: 5.65s
1577:	learn: 0.0564507	total: 6m 27s	remaining: 5.41s
1578:	learn: 0.0564505	total: 6m 28s	remaining: 5.16s
1579:	learn: 0.0564503	total: 6m 28s	remaining: 4.91s
1580:	learn: 0.0564501	total: 6m 28s	remaining: 4.67s
1581:	learn: 0.0564499	total: 6m 28s	remaining: 4.42s
1582:	learn: 0.0564498	total: 6m 28s	remaining: 4.18s
1583:	learn: 0.0564496	total: 6m 29s	remaining: 3.93s
1584:	learn: 0.0564494	total: 6m 29s	remaining: 3.68s
1585:	learn: 0.0564491	total: 6m 29s	remaining: 3.44s
1586:	learn: 0.0564489	total: 6m 29s	remaining: 3.19s
1587:	learn: 0.0564486	total: 6m 30s	remaining: 2.95s
1588:	learn: 0.0564484	total: 6m 30s	remaining: 2.7s
1589:	learn: 0.0564482	total: 6m 30s	remaining: 2.46s
1590:	learn: 0.0564480	total: 6m 30s	remaining: 2.21s
1591:	learn: 0.0564477	total: 6m 31s	remaining: 1.97s
1592:	learn: 0.0564475	total: 6m 31s	remaining: 1.72s
1593:	learn: 0.0564474	total: 6m 31s	remaining: 1.47s
1594:	learn: 0.0564470	total: 6m 31s	remaining: 1.23s
1595:	learn: 0.0564467	total: 6m 31s	remaining: 982ms
1596:	learn: 0.0564465	total: 6m 31s	remaining: 736ms
1597:	learn: 0.0564462	total: 6m 32s	remaining: 491ms
1598:	learn: 0.0564460	total: 6m 32s	remaining: 245ms
1599:	learn: 0.0564457	total: 6m 32s	remaining: 0us
1534:	learn: 0.0563511	total: 5m 45s	remaining: 14.6s
1535:	learn: 0.0563508	total: 5m 45s	remaining: 14.4s
1536:	learn: 0.0563506	total: 5m 45s	remaining: 14.2s
1537:	learn: 0.0563503	total: 5m 45s	remaining: 13.9s
1538:	learn: 0.0563501	total: 5m 45s	remaining: 13.7s
1539:	learn: 0.0563498	total: 5m 46s	remaining: 13.5s
1540:	learn: 0.0563496	total: 5m 46s	remaining: 13.3s
1541:	learn: 0.0563494	total: 5m 46s	remaining: 13s
1542:	learn: 0.0563492	total: 5m 46s	remaining: 12.8s
1543:	learn: 0.0563490	total: 5m 46s	remaining: 12.6s
1544:	learn: 0.0563488	total: 5m 46s	remaining: 12.3s
1545:	learn: 0.0563485	total: 5m 46s	remaining: 12.1s
1546:	learn: 0.0563484	total: 5m 46s	remaining: 11.9s
1547:	learn: 0.0563482	total: 5m 46s	remaining: 11.7s
1548:	learn: 0.0563480	total: 5m 47s	remaining: 11.4s
1549:	learn: 0.0563477	total: 5m 47s	remaining: 11.2s
1550:	learn: 0.0563475	total: 5m 47s	remaining: 11s
1551:	learn: 0.0563472	total: 5m 47s	remaining: 10.7s
1552:	learn: 0.0563470	total: 5m 47s	remaining: 10.5s
1553:	learn: 0.0563468	total: 5m 47s	remaining: 10.3s
1554:	learn: 0.0563467	total: 5m 47s	remaining: 10.1s
1555:	learn: 0.0563465	total: 5m 47s	remaining: 9.83s
1556:	learn: 0.0563464	total: 5m 47s	remaining: 9.61s
1557:	learn: 0.0563461	total: 5m 48s	remaining: 9.38s
1558:	learn: 0.0563458	total: 5m 48s	remaining: 9.15s
1559:	learn: 0.0563456	total: 5m 48s	remaining: 8.93s
1560:	learn: 0.0563453	total: 5m 48s	remaining: 8.7s
1561:	learn: 0.0563451	total: 5m 48s	remaining: 8.48s
1562:	learn: 0.0563448	total: 5m 48s	remaining: 8.25s
1563:	learn: 0.0563446	total: 5m 48s	remaining: 8.03s
1564:	learn: 0.0563445	total: 5m 48s	remaining: 7.8s
1565:	learn: 0.0563443	total: 5m 48s	remaining: 7.57s
1566:	learn: 0.0563440	total: 5m 48s	remaining: 7.35s
1567:	learn: 0.0563437	total: 5m 49s	remaining: 7.12s
1568:	learn: 0.0563434	total: 5m 49s	remaining: 6.9s
1569:	learn: 0.0563431	total: 5m 49s	remaining: 6.67s
1570:	learn: 0.0563428	total: 5m 49s	remaining: 6.45s
1571:	learn: 0.0563425	total: 5m 49s	remaining: 6.23s
1572:	learn: 0.0563422	total: 5m 49s	remaining: 6s
1573:	learn: 0.0563420	total: 5m 49s	remaining: 5.78s
1574:	learn: 0.0563417	total: 5m 50s	remaining: 5.56s
1575:	learn: 0.0563415	total: 5m 50s	remaining: 5.33s
1576:	learn: 0.0563414	total: 5m 50s	remaining: 5.11s
1577:	learn: 0.0563411	total: 5m 50s	remaining: 4.88s
1578:	learn: 0.0563409	total: 5m 50s	remaining: 4.66s
1579:	learn: 0.0563407	total: 5m 50s	remaining: 4.44s
1580:	learn: 0.0563405	total: 5m 50s	remaining: 4.21s
1581:	learn: 0.0563402	total: 5m 50s	remaining: 3.99s
1582:	learn: 0.0563399	total: 5m 50s	remaining: 3.77s
1583:	learn: 0.0563397	total: 5m 51s	remaining: 3.54s
1584:	learn: 0.0563395	total: 5m 51s	remaining: 3.32s
1585:	learn: 0.0563391	total: 5m 51s	remaining: 3.1s
1586:	learn: 0.0563389	total: 5m 51s	remaining: 2.88s
1587:	learn: 0.0563386	total: 5m 51s	remaining: 2.65s
1588:	learn: 0.0563384	total: 5m 51s	remaining: 2.43s
1589:	learn: 0.0563382	total: 5m 51s	remaining: 2.21s
1590:	learn: 0.0563380	total: 5m 51s	remaining: 1.99s
1591:	learn: 0.0563378	total: 5m 51s	remaining: 1.77s
1592:	learn: 0.0563376	total: 5m 51s	remaining: 1.55s
1593:	learn: 0.0563373	total: 5m 52s	remaining: 1.32s
1594:	learn: 0.0563372	total: 5m 52s	remaining: 1.1s
1595:	learn: 0.0563369	total: 5m 52s	remaining: 883ms
1596:	learn: 0.0563367	total: 5m 52s	remaining: 662ms
1597:	learn: 0.0563365	total: 5m 52s	remaining: 441ms
1598:	learn: 0.0563362	total: 5m 52s	remaining: 221ms
1599:	learn: 0.0563360	total: 5m 52s	remaining: 0us
1507:	learn: 0.0564338	total: 1m 28s	remaining: 5.39s
1508:	learn: 0.0564336	total: 1m 28s	remaining: 5.33s
1509:	learn: 0.0564334	total: 1m 28s	remaining: 5.27s
1510:	learn: 0.0564331	total: 1m 28s	remaining: 5.21s
1511:	learn: 0.0564330	total: 1m 28s	remaining: 5.16s
1512:	learn: 0.0564328	total: 1m 28s	remaining: 5.1s
1513:	learn: 0.0564326	total: 1m 28s	remaining: 5.04s
1514:	learn: 0.0564322	total: 1m 28s	remaining: 4.98s
1515:	learn: 0.0564320	total: 1m 28s	remaining: 4.92s
1516:	learn: 0.0564317	total: 1m 28s	remaining: 4.86s
1517:	learn: 0.0564315	total: 1m 28s	remaining: 4.8s
1518:	learn: 0.0564311	total: 1m 28s	remaining: 4.74s
1519:	learn: 0.0564310	total: 1m 28s	remaining: 4.68s
1520:	learn: 0.0564308	total: 1m 29s	remaining: 4.62s
1521:	learn: 0.0564306	total: 1m 29s	remaining: 4.56s
1522:	learn: 0.0564304	total: 1m 29s	remaining: 4.5s
1523:	learn: 0.0564303	total: 1m 29s	remaining: 4.45s
1524:	learn: 0.0564301	total: 1m 29s	remaining: 4.39s
1525:	learn: 0.0564300	total: 1m 29s	remaining: 4.33s
1526:	learn: 0.0564298	total: 1m 29s	remaining: 4.27s
1527:	learn: 0.0564296	total: 1m 29s	remaining: 4.21s
1528:	learn: 0.0564293	total: 1m 29s	remaining: 4.15s
1529:	learn: 0.0564291	total: 1m 29s	remaining: 4.09s
1530:	learn: 0.0564287	total: 1m 29s	remaining: 4.03s
1531:	learn: 0.0564285	total: 1m 29s	remaining: 3.97s
1532:	learn: 0.0564282	total: 1m 29s	remaining: 3.92s
1533:	learn: 0.0564280	total: 1m 29s	remaining: 3.86s
1534:	learn: 0.0564277	total: 1m 29s	remaining: 3.8s
1535:	learn: 0.0564276	total: 1m 29s	remaining: 3.74s
1536:	learn: 0.0564273	total: 1m 29s	remaining: 3.68s
1537:	learn: 0.0564271	total: 1m 29s	remaining: 3.62s
1538:	learn: 0.0564266	total: 1m 29s	remaining: 3.56s
1539:	learn: 0.0564264	total: 1m 29s	remaining: 3.5s
1540:	learn: 0.0564261	total: 1m 29s	remaining: 3.44s
1541:	learn: 0.0564260	total: 1m 30s	remaining: 3.39s
1542:	learn: 0.0564257	total: 1m 30s	remaining: 3.33s
1543:	learn: 0.0564254	total: 1m 30s	remaining: 3.27s
1544:	learn: 0.0564252	total: 1m 30s	remaining: 3.21s
1545:	learn: 0.0564249	total: 1m 30s	remaining: 3.15s
1546:	learn: 0.0564247	total: 1m 30s	remaining: 3.09s
1547:	learn: 0.0564245	total: 1m 30s	remaining: 3.03s
1548:	learn: 0.0564243	total: 1m 30s	remaining: 2.98s
1549:	learn: 0.0564241	total: 1m 30s	remaining: 2.92s
1550:	learn: 0.0564238	total: 1m 30s	remaining: 2.86s
1551:	learn: 0.0564235	total: 1m 30s	remaining: 2.8s
1552:	learn: 0.0564233	total: 1m 30s	remaining: 2.74s
1553:	learn: 0.0564232	total: 1m 30s	remaining: 2.68s
1554:	learn: 0.0564230	total: 1m 30s	remaining: 2.62s
1555:	learn: 0.0564227	total: 1m 30s	remaining: 2.56s
1556:	learn: 0.0564225	total: 1m 30s	remaining: 2.51s
1557:	learn: 0.0564223	total: 1m 30s	remaining: 2.45s
1558:	learn: 0.0564222	total: 1m 30s	remaining: 2.39s
1559:	learn: 0.0564219	total: 1m 30s	remaining: 2.33s
1560:	learn: 0.0564216	total: 1m 30s	remaining: 2.27s
1561:	learn: 0.0564213	total: 1m 31s	remaining: 2.21s
1562:	learn: 0.0564211	total: 1m 31s	remaining: 2.15s
1563:	learn: 0.0564209	total: 1m 31s	remaining: 2.1s
1564:	learn: 0.0564206	total: 1m 31s	remaining: 2.04s
1565:	learn: 0.0564205	total: 1m 31s	remaining: 1.98s
1566:	learn: 0.0564203	total: 1m 31s	remaining: 1.92s
1567:	learn: 0.0564201	total: 1m 31s	remaining: 1.86s
1568:	learn: 0.0564199	total: 1m 31s	remaining: 1.8s
1569:	learn: 0.0564196	total: 1m 31s	remaining: 1.75s
1570:	learn: 0.0564193	total: 1m 31s	remaining: 1.69s
1571:	learn: 0.0564192	total: 1m 31s	remaining: 1.63s
1572:	learn: 0.0564190	total: 1m 31s	remaining: 1.57s
1573:	learn: 0.0564188	total: 1m 31s	remaining: 1.51s
1574:	learn: 0.0564186	total: 1m 31s	remaining: 1.45s
1575:	learn: 0.0564183	total: 1m 31s	remaining: 1.4s
1576:	learn: 0.0564181	total: 1m 31s	remaining: 1.34s
1577:	learn: 0.0564179	total: 1m 31s	remaining: 1.28s
1578:	learn: 0.0564176	total: 1m 31s	remaining: 1.22s
1579:	learn: 0.0564175	total: 1m 31s	remaining: 1.16s
1580:	learn: 0.0564172	total: 1m 31s	remaining: 1.1s
1581:	learn: 0.0564170	total: 1m 31s	remaining: 1.05s
1582:	learn: 0.0564167	total: 1m 32s	remaining: 988ms
1583:	learn: 0.0564165	total: 1m 32s	remaining: 930ms
1584:	learn: 0.0564162	total: 1m 32s	remaining: 872ms
1585:	learn: 0.0564161	total: 1m 32s	remaining: 813ms
1586:	learn: 0.0564158	total: 1m 32s	remaining: 755ms
1587:	learn: 0.0564157	total: 1m 32s	remaining: 697ms
1588:	learn: 0.0564155	total: 1m 32s	remaining: 639ms
1589:	learn: 0.0564153	total: 1m 32s	remaining: 581ms
1590:	learn: 0.0564152	total: 1m 32s	remaining: 523ms
1591:	learn: 0.0564150	total: 1m 32s	remaining: 465ms
1592:	learn: 0.0564148	total: 1m 32s	remaining: 406ms
1593:	learn: 0.0564145	total: 1m 32s	remaining: 348ms
1594:	learn: 0.0564143	total: 1m 32s	remaining: 290ms
1595:	learn: 0.0564141	total: 1m 32s	remaining: 232ms
1596:	learn: 0.0564139	total: 1m 32s	remaining: 174ms
1597:	learn: 0.0564136	total: 1m 32s	remaining: 116ms
1598:	learn: 0.0564134	total: 1m 32s	remaining: 58ms
1599:	learn: 0.0564133	total: 1m 32s	remaining: 0us

In [17]:
cat = CatBoostRegressor(
    subsample=1.0,
    random_strength=5,
    min_data_in_leaf=10,
    learning_rate=0.1,
    leaf_estimation_iterations=1,
    l2_leaf_reg=5,
    iterations=800,
    grow_policy='SymmetricTree',
    depth=7,
    border_count=128,
    bootstrap_type='MVS',
    bagging_temperature=0.5
)
cat.fit(X_train, y_train)
y_pred = cat.predict(X_test)

print('MSE for catboost:', mean_squared_error(y_test, y_pred))
print('R2 for catboost:', r2_score(y_test, y_pred))

0:	learn: 0.1528891	total: 54.6ms	remaining: 43.6s
1:	learn: 0.1408864	total: 96.7ms	remaining: 38.6s
2:	learn: 0.1306697	total: 129ms	remaining: 34.1s
3:	learn: 0.1204629	total: 167ms	remaining: 33.3s
4:	learn: 0.1114676	total: 206ms	remaining: 32.7s
5:	learn: 0.1035307	total: 251ms	remaining: 33.2s
6:	learn: 0.0966303	total: 291ms	remaining: 33s
7:	learn: 0.0906715	total: 326ms	remaining: 32.3s
8:	learn: 0.0854478	total: 361ms	remaining: 31.7s
9:	learn: 0.0814030	total: 399ms	remaining: 31.5s
10:	learn: 0.0777586	total: 445ms	remaining: 31.9s
11:	learn: 0.0745660	total: 476ms	remaining: 31.3s
12:	learn: 0.0717214	total: 516ms	remaining: 31.2s
13:	learn: 0.0692291	total: 553ms	remaining: 31s
14:	learn: 0.0671523	total: 589ms	remaining: 30.8s
15:	learn: 0.0655102	total: 626ms	remaining: 30.7s
16:	learn: 0.0641128	total: 665ms	remaining: 30.6s
17:	learn: 0.0628788	total: 698ms	remaining: 30.3s
18:	learn: 0.0619514	total: 735ms	remaining: 30.2s
19:	learn: 0.0611610	total: 772ms	remaining: 30.1s
20:	learn: 0.0605142	total: 808ms	remaining: 30s
21:	learn: 0.0599738	total: 846ms	remaining: 29.9s
22:	learn: 0.0594570	total: 883ms	remaining: 29.8s
23:	learn: 0.0590087	total: 919ms	remaining: 29.7s
24:	learn: 0.0587018	total: 958ms	remaining: 29.7s
25:	learn: 0.0583784	total: 995ms	remaining: 29.6s
26:	learn: 0.0581148	total: 1.03s	remaining: 29.5s
27:	learn: 0.0579144	total: 1.07s	remaining: 29.4s
28:	learn: 0.0577491	total: 1.1s	remaining: 29.3s
29:	learn: 0.0576052	total: 1.14s	remaining: 29.3s
30:	learn: 0.0574924	total: 1.18s	remaining: 29.2s
31:	learn: 0.0574181	total: 1.2s	remaining: 28.9s
32:	learn: 0.0573326	total: 1.24s	remaining: 28.8s
33:	learn: 0.0572557	total: 1.27s	remaining: 28.7s
34:	learn: 0.0571830	total: 1.31s	remaining: 28.6s
35:	learn: 0.0571107	total: 1.34s	remaining: 28.5s
36:	learn: 0.0570603	total: 1.38s	remaining: 28.5s
37:	learn: 0.0570137	total: 1.42s	remaining: 28.5s
38:	learn: 0.0569618	total: 1.46s	remaining: 28.4s
39:	learn: 0.0569119	total: 1.49s	remaining: 28.4s
40:	learn: 0.0568772	total: 1.53s	remaining: 28.3s
41:	learn: 0.0568384	total: 1.57s	remaining: 28.3s
42:	learn: 0.0568034	total: 1.6s	remaining: 28.3s
43:	learn: 0.0567811	total: 1.64s	remaining: 28.2s
44:	learn: 0.0567625	total: 1.68s	remaining: 28.1s
45:	learn: 0.0567411	total: 1.71s	remaining: 28.1s
46:	learn: 0.0567272	total: 1.75s	remaining: 28s
47:	learn: 0.0567150	total: 1.79s	remaining: 28s
48:	learn: 0.0567057	total: 1.83s	remaining: 28s
49:	learn: 0.0566899	total: 1.87s	remaining: 28s
50:	learn: 0.0566736	total: 1.9s	remaining: 28s
51:	learn: 0.0566623	total: 1.94s	remaining: 27.9s
52:	learn: 0.0566511	total: 1.98s	remaining: 27.9s
53:	learn: 0.0566495	total: 2s	remaining: 27.6s
54:	learn: 0.0566377	total: 2.04s	remaining: 27.7s
55:	learn: 0.0566269	total: 2.08s	remaining: 27.6s
56:	learn: 0.0566205	total: 2.11s	remaining: 27.5s
57:	learn: 0.0566069	total: 2.16s	remaining: 27.6s
58:	learn: 0.0566025	total: 2.19s	remaining: 27.5s
59:	learn: 0.0565880	total: 2.23s	remaining: 27.5s
60:	learn: 0.0565830	total: 2.28s	remaining: 27.6s
61:	learn: 0.0565718	total: 2.33s	remaining: 27.7s
62:	learn: 0.0565676	total: 2.37s	remaining: 27.7s
63:	learn: 0.0565623	total: 2.4s	remaining: 27.7s
64:	learn: 0.0565588	total: 2.45s	remaining: 27.7s
65:	learn: 0.0565546	total: 2.49s	remaining: 27.7s
66:	learn: 0.0565511	total: 2.52s	remaining: 27.6s
67:	learn: 0.0565413	total: 2.56s	remaining: 27.6s
68:	learn: 0.0565295	total: 2.6s	remaining: 27.6s
69:	learn: 0.0565263	total: 2.64s	remaining: 27.6s
70:	learn: 0.0565172	total: 2.68s	remaining: 27.5s
71:	learn: 0.0565121	total: 2.71s	remaining: 27.4s
72:	learn: 0.0565084	total: 2.75s	remaining: 27.4s
73:	learn: 0.0565018	total: 2.79s	remaining: 27.4s
74:	learn: 0.0564957	total: 2.83s	remaining: 27.4s
75:	learn: 0.0564943	total: 2.86s	remaining: 27.2s
76:	learn: 0.0564883	total: 2.89s	remaining: 27.2s
77:	learn: 0.0564848	total: 2.94s	remaining: 27.2s
78:	learn: 0.0564762	total: 2.98s	remaining: 27.2s
79:	learn: 0.0564752	total: 3.02s	remaining: 27.2s
80:	learn: 0.0564690	total: 3.06s	remaining: 27.2s
81:	learn: 0.0564619	total: 3.11s	remaining: 27.2s
82:	learn: 0.0564581	total: 3.16s	remaining: 27.3s
83:	learn: 0.0564552	total: 3.2s	remaining: 27.2s
84:	learn: 0.0564546	total: 3.22s	remaining: 27.1s
85:	learn: 0.0564514	total: 3.26s	remaining: 27.1s
86:	learn: 0.0564499	total: 3.29s	remaining: 27s
87:	learn: 0.0564477	total: 3.33s	remaining: 26.9s
88:	learn: 0.0564464	total: 3.37s	remaining: 26.9s
89:	learn: 0.0564425	total: 3.4s	remaining: 26.8s
90:	learn: 0.0564396	total: 3.44s	remaining: 26.8s
91:	learn: 0.0564372	total: 3.47s	remaining: 26.7s
92:	learn: 0.0564351	total: 3.5s	remaining: 26.6s
93:	learn: 0.0564348	total: 3.53s	remaining: 26.5s
94:	learn: 0.0564344	total: 3.56s	remaining: 26.4s
95:	learn: 0.0564311	total: 3.6s	remaining: 26.4s
96:	learn: 0.0564293	total: 3.64s	remaining: 26.4s
97:	learn: 0.0564280	total: 3.68s	remaining: 26.4s
98:	learn: 0.0564261	total: 3.71s	remaining: 26.3s
99:	learn: 0.0564236	total: 3.75s	remaining: 26.3s
100:	learn: 0.0564221	total: 3.79s	remaining: 26.2s
101:	learn: 0.0564176	total: 3.83s	remaining: 26.2s
102:	learn: 0.0564173	total: 3.85s	remaining: 26.1s
103:	learn: 0.0564143	total: 3.89s	remaining: 26s
104:	learn: 0.0564132	total: 3.92s	remaining: 26s
105:	learn: 0.0564104	total: 3.96s	remaining: 25.9s
106:	learn: 0.0564040	total: 4s	remaining: 25.9s
107:	learn: 0.0564021	total: 4.03s	remaining: 25.8s
108:	learn: 0.0564006	total: 4.07s	remaining: 25.8s
109:	learn: 0.0563984	total: 4.1s	remaining: 25.7s
110:	learn: 0.0563962	total: 4.14s	remaining: 25.7s
111:	learn: 0.0563925	total: 4.18s	remaining: 25.7s
112:	learn: 0.0563922	total: 4.21s	remaining: 25.6s
113:	learn: 0.0563921	total: 4.24s	remaining: 25.5s
114:	learn: 0.0563914	total: 4.28s	remaining: 25.5s
115:	learn: 0.0563897	total: 4.31s	remaining: 25.4s
116:	learn: 0.0563888	total: 4.35s	remaining: 25.4s
117:	learn: 0.0563859	total: 4.39s	remaining: 25.4s
118:	learn: 0.0563805	total: 4.43s	remaining: 25.3s
119:	learn: 0.0563772	total: 4.46s	remaining: 25.3s
120:	learn: 0.0563769	total: 4.49s	remaining: 25.2s
121:	learn: 0.0563769	total: 4.51s	remaining: 25.1s
122:	learn: 0.0563716	total: 4.55s	remaining: 25s
123:	learn: 0.0563674	total: 4.59s	remaining: 25s
124:	learn: 0.0563656	total: 4.62s	remaining: 25s
125:	learn: 0.0563645	total: 4.66s	remaining: 24.9s
126:	learn: 0.0563645	total: 4.68s	remaining: 24.8s
127:	learn: 0.0563592	total: 4.72s	remaining: 24.8s
128:	learn: 0.0563544	total: 4.75s	remaining: 24.7s
129:	learn: 0.0563494	total: 4.79s	remaining: 24.7s
130:	learn: 0.0563490	total: 4.82s	remaining: 24.6s
131:	learn: 0.0563470	total: 4.85s	remaining: 24.6s
132:	learn: 0.0563434	total: 4.89s	remaining: 24.5s
133:	learn: 0.0563384	total: 4.94s	remaining: 24.5s
134:	learn: 0.0563353	total: 4.98s	remaining: 24.5s
135:	learn: 0.0563333	total: 5.01s	remaining: 24.5s
136:	learn: 0.0563291	total: 5.05s	remaining: 24.5s
137:	learn: 0.0563253	total: 5.11s	remaining: 24.5s
138:	learn: 0.0563220	total: 5.17s	remaining: 24.6s
139:	learn: 0.0563146	total: 5.21s	remaining: 24.6s
140:	learn: 0.0563119	total: 5.25s	remaining: 24.5s
141:	learn: 0.0563059	total: 5.29s	remaining: 24.5s
142:	learn: 0.0563031	total: 5.33s	remaining: 24.5s
143:	learn: 0.0563003	total: 5.36s	remaining: 24.4s
144:	learn: 0.0562968	total: 5.4s	remaining: 24.4s
145:	learn: 0.0562910	total: 5.43s	remaining: 24.3s
146:	learn: 0.0562860	total: 5.47s	remaining: 24.3s
147:	learn: 0.0562798	total: 5.5s	remaining: 24.2s
148:	learn: 0.0562736	total: 5.54s	remaining: 24.2s
149:	learn: 0.0562695	total: 5.57s	remaining: 24.1s
150:	learn: 0.0562661	total: 5.6s	remaining: 24.1s
151:	learn: 0.0562622	total: 5.63s	remaining: 24s
152:	learn: 0.0562579	total: 5.67s	remaining: 24s
153:	learn: 0.0562535	total: 5.7s	remaining: 23.9s
154:	learn: 0.0562481	total: 5.74s	remaining: 23.9s
155:	learn: 0.0562447	total: 5.77s	remaining: 23.8s
156:	learn: 0.0562410	total: 5.8s	remaining: 23.8s
157:	learn: 0.0562363	total: 5.84s	remaining: 23.7s
158:	learn: 0.0562320	total: 5.87s	remaining: 23.7s
159:	learn: 0.0562279	total: 5.91s	remaining: 23.6s
160:	learn: 0.0562250	total: 5.94s	remaining: 23.6s
161:	learn: 0.0562213	total: 5.98s	remaining: 23.5s
162:	learn: 0.0562182	total: 6.01s	remaining: 23.5s
163:	learn: 0.0562156	total: 6.04s	remaining: 23.4s
164:	learn: 0.0562116	total: 6.08s	remaining: 23.4s
165:	learn: 0.0562083	total: 6.11s	remaining: 23.4s
166:	learn: 0.0562043	total: 6.15s	remaining: 23.3s
167:	learn: 0.0562005	total: 6.18s	remaining: 23.3s
168:	learn: 0.0561971	total: 6.22s	remaining: 23.2s
169:	learn: 0.0561910	total: 6.26s	remaining: 23.2s
170:	learn: 0.0561869	total: 6.3s	remaining: 23.2s
171:	learn: 0.0561836	total: 6.33s	remaining: 23.1s
172:	learn: 0.0561798	total: 6.37s	remaining: 23.1s
173:	learn: 0.0561771	total: 6.4s	remaining: 23s
174:	learn: 0.0561734	total: 6.43s	remaining: 23s
175:	learn: 0.0561695	total: 6.46s	remaining: 22.9s
176:	learn: 0.0561654	total: 6.5s	remaining: 22.9s
177:	learn: 0.0561625	total: 6.53s	remaining: 22.8s
178:	learn: 0.0561609	total: 6.56s	remaining: 22.8s
179:	learn: 0.0561584	total: 6.6s	remaining: 22.7s
180:	learn: 0.0561557	total: 6.64s	remaining: 22.7s
181:	learn: 0.0561506	total: 6.67s	remaining: 22.7s
182:	learn: 0.0561473	total: 6.71s	remaining: 22.6s
183:	learn: 0.0561444	total: 6.74s	remaining: 22.6s
184:	learn: 0.0561402	total: 6.78s	remaining: 22.5s
185:	learn: 0.0561373	total: 6.82s	remaining: 22.5s
186:	learn: 0.0561318	total: 6.85s	remaining: 22.5s
187:	learn: 0.0561291	total: 6.88s	remaining: 22.4s
188:	learn: 0.0561267	total: 6.92s	remaining: 22.4s
189:	learn: 0.0561248	total: 6.96s	remaining: 22.4s
190:	learn: 0.0561223	total: 7.02s	remaining: 22.4s
191:	learn: 0.0561200	total: 7.05s	remaining: 22.3s
192:	learn: 0.0561167	total: 7.09s	remaining: 22.3s
193:	learn: 0.0561143	total: 7.13s	remaining: 22.3s
194:	learn: 0.0561124	total: 7.16s	remaining: 22.2s
195:	learn: 0.0561099	total: 7.19s	remaining: 22.2s
196:	learn: 0.0561030	total: 7.24s	remaining: 22.1s
197:	learn: 0.0561000	total: 7.27s	remaining: 22.1s
198:	learn: 0.0560977	total: 7.3s	remaining: 22.1s
199:	learn: 0.0560955	total: 7.34s	remaining: 22s
200:	learn: 0.0560938	total: 7.38s	remaining: 22s
201:	learn: 0.0560917	total: 7.42s	remaining: 22s
202:	learn: 0.0560902	total: 7.46s	remaining: 21.9s
203:	learn: 0.0560868	total: 7.5s	remaining: 21.9s
204:	learn: 0.0560850	total: 7.54s	remaining: 21.9s
205:	learn: 0.0560833	total: 7.57s	remaining: 21.8s
206:	learn: 0.0560816	total: 7.6s	remaining: 21.8s
207:	learn: 0.0560793	total: 7.64s	remaining: 21.7s
208:	learn: 0.0560770	total: 7.68s	remaining: 21.7s
209:	learn: 0.0560742	total: 7.71s	remaining: 21.7s
210:	learn: 0.0560712	total: 7.75s	remaining: 21.6s
211:	learn: 0.0560696	total: 7.78s	remaining: 21.6s
212:	learn: 0.0560681	total: 7.82s	remaining: 21.5s
213:	learn: 0.0560651	total: 7.85s	remaining: 21.5s
214:	learn: 0.0560630	total: 7.89s	remaining: 21.5s
215:	learn: 0.0560612	total: 7.93s	remaining: 21.4s
216:	learn: 0.0560570	total: 7.97s	remaining: 21.4s
217:	learn: 0.0560549	total: 8s	remaining: 21.4s
218:	learn: 0.0560524	total: 8.04s	remaining: 21.3s
219:	learn: 0.0560509	total: 8.07s	remaining: 21.3s
220:	learn: 0.0560480	total: 8.1s	remaining: 21.2s
221:	learn: 0.0560455	total: 8.14s	remaining: 21.2s
222:	learn: 0.0560437	total: 8.18s	remaining: 21.2s
223:	learn: 0.0560417	total: 8.21s	remaining: 21.1s
224:	learn: 0.0560393	total: 8.25s	remaining: 21.1s
225:	learn: 0.0560373	total: 8.28s	remaining: 21s
226:	learn: 0.0560355	total: 8.32s	remaining: 21s
227:	learn: 0.0560334	total: 8.36s	remaining: 21s
228:	learn: 0.0560312	total: 8.39s	remaining: 20.9s
229:	learn: 0.0560293	total: 8.42s	remaining: 20.9s
230:	learn: 0.0560273	total: 8.46s	remaining: 20.8s
231:	learn: 0.0560253	total: 8.49s	remaining: 20.8s
232:	learn: 0.0560235	total: 8.53s	remaining: 20.8s
233:	learn: 0.0560216	total: 8.56s	remaining: 20.7s
234:	learn: 0.0560190	total: 8.6s	remaining: 20.7s
235:	learn: 0.0560134	total: 8.64s	remaining: 20.6s
236:	learn: 0.0560104	total: 8.67s	remaining: 20.6s
237:	learn: 0.0560090	total: 8.71s	remaining: 20.6s
238:	learn: 0.0560073	total: 8.75s	remaining: 20.5s
239:	learn: 0.0560054	total: 8.78s	remaining: 20.5s
240:	learn: 0.0560038	total: 8.81s	remaining: 20.4s
241:	learn: 0.0560015	total: 8.85s	remaining: 20.4s
242:	learn: 0.0559997	total: 8.88s	remaining: 20.4s
243:	learn: 0.0559979	total: 8.92s	remaining: 20.3s
244:	learn: 0.0559969	total: 8.95s	remaining: 20.3s
245:	learn: 0.0559952	total: 8.99s	remaining: 20.2s
246:	learn: 0.0559936	total: 9.02s	remaining: 20.2s
247:	learn: 0.0559925	total: 9.05s	remaining: 20.2s
248:	learn: 0.0559909	total: 9.09s	remaining: 20.1s
249:	learn: 0.0559896	total: 9.13s	remaining: 20.1s
250:	learn: 0.0559856	total: 9.17s	remaining: 20.1s
251:	learn: 0.0559837	total: 9.21s	remaining: 20s
252:	learn: 0.0559818	total: 9.25s	remaining: 20s
253:	learn: 0.0559788	total: 9.28s	remaining: 20s
254:	learn: 0.0559771	total: 9.31s	remaining: 19.9s
255:	learn: 0.0559760	total: 9.35s	remaining: 19.9s
256:	learn: 0.0559746	total: 9.38s	remaining: 19.8s
257:	learn: 0.0559719	total: 9.42s	remaining: 19.8s
258:	learn: 0.0559702	total: 9.46s	remaining: 19.8s
259:	learn: 0.0559685	total: 9.49s	remaining: 19.7s
260:	learn: 0.0559656	total: 9.53s	remaining: 19.7s
261:	learn: 0.0559638	total: 9.56s	remaining: 19.6s
262:	learn: 0.0559624	total: 9.6s	remaining: 19.6s
263:	learn: 0.0559608	total: 9.64s	remaining: 19.6s
264:	learn: 0.0559564	total: 9.68s	remaining: 19.5s
265:	learn: 0.0559548	total: 9.71s	remaining: 19.5s
266:	learn: 0.0559537	total: 9.75s	remaining: 19.5s
267:	learn: 0.0559515	total: 9.79s	remaining: 19.4s
268:	learn: 0.0559501	total: 9.83s	remaining: 19.4s
269:	learn: 0.0559487	total: 9.86s	remaining: 19.4s
270:	learn: 0.0559471	total: 9.9s	remaining: 19.3s
271:	learn: 0.0559456	total: 9.93s	remaining: 19.3s
272:	learn: 0.0559443	total: 9.97s	remaining: 19.3s
273:	learn: 0.0559423	total: 10s	remaining: 19.2s
274:	learn: 0.0559416	total: 10s	remaining: 19.2s
275:	learn: 0.0559401	total: 10.1s	remaining: 19.1s
276:	learn: 0.0559386	total: 10.1s	remaining: 19.1s
277:	learn: 0.0559365	total: 10.2s	remaining: 19.1s
278:	learn: 0.0559340	total: 10.2s	remaining: 19s
279:	learn: 0.0559316	total: 10.2s	remaining: 19s
280:	learn: 0.0559294	total: 10.3s	remaining: 18.9s
281:	learn: 0.0559285	total: 10.3s	remaining: 18.9s
282:	learn: 0.0559265	total: 10.3s	remaining: 18.9s
283:	learn: 0.0559251	total: 10.4s	remaining: 18.8s
284:	learn: 0.0559231	total: 10.4s	remaining: 18.8s
285:	learn: 0.0559222	total: 10.4s	remaining: 18.8s
286:	learn: 0.0559202	total: 10.5s	remaining: 18.7s
287:	learn: 0.0559185	total: 10.5s	remaining: 18.7s
288:	learn: 0.0559171	total: 10.6s	remaining: 18.7s
289:	learn: 0.0559159	total: 10.6s	remaining: 18.6s
290:	learn: 0.0559141	total: 10.6s	remaining: 18.6s
291:	learn: 0.0559129	total: 10.7s	remaining: 18.6s
292:	learn: 0.0559114	total: 10.7s	remaining: 18.5s
293:	learn: 0.0559098	total: 10.7s	remaining: 18.5s
294:	learn: 0.0559085	total: 10.8s	remaining: 18.5s
295:	learn: 0.0559073	total: 10.8s	remaining: 18.4s
296:	learn: 0.0559063	total: 10.9s	remaining: 18.4s
297:	learn: 0.0559050	total: 10.9s	remaining: 18.3s
298:	learn: 0.0559038	total: 10.9s	remaining: 18.3s
299:	learn: 0.0559014	total: 11s	remaining: 18.3s
300:	learn: 0.0559000	total: 11s	remaining: 18.2s
301:	learn: 0.0558983	total: 11s	remaining: 18.2s
302:	learn: 0.0558965	total: 11.1s	remaining: 18.2s
303:	learn: 0.0558953	total: 11.1s	remaining: 18.1s
304:	learn: 0.0558937	total: 11.1s	remaining: 18.1s
305:	learn: 0.0558922	total: 11.2s	remaining: 18s
306:	learn: 0.0558904	total: 11.2s	remaining: 18s
307:	learn: 0.0558869	total: 11.2s	remaining: 18s
308:	learn: 0.0558859	total: 11.3s	remaining: 17.9s
309:	learn: 0.0558844	total: 11.3s	remaining: 17.9s
310:	learn: 0.0558827	total: 11.4s	remaining: 17.9s
311:	learn: 0.0558809	total: 11.4s	remaining: 17.8s
312:	learn: 0.0558788	total: 11.4s	remaining: 17.8s
313:	learn: 0.0558773	total: 11.5s	remaining: 17.8s
314:	learn: 0.0558759	total: 11.5s	remaining: 17.7s
315:	learn: 0.0558745	total: 11.5s	remaining: 17.7s
316:	learn: 0.0558728	total: 11.6s	remaining: 17.6s
317:	learn: 0.0558718	total: 11.6s	remaining: 17.6s
318:	learn: 0.0558703	total: 11.7s	remaining: 17.6s
319:	learn: 0.0558686	total: 11.7s	remaining: 17.6s
320:	learn: 0.0558668	total: 11.7s	remaining: 17.5s
321:	learn: 0.0558652	total: 11.8s	remaining: 17.5s
322:	learn: 0.0558636	total: 11.8s	remaining: 17.5s
323:	learn: 0.0558617	total: 11.9s	remaining: 17.4s
324:	learn: 0.0558603	total: 11.9s	remaining: 17.4s
325:	learn: 0.0558592	total: 11.9s	remaining: 17.4s
326:	learn: 0.0558573	total: 12s	remaining: 17.3s
327:	learn: 0.0558564	total: 12s	remaining: 17.3s
328:	learn: 0.0558552	total: 12.1s	remaining: 17.3s
329:	learn: 0.0558539	total: 12.1s	remaining: 17.3s
330:	learn: 0.0558525	total: 12.2s	remaining: 17.2s
331:	learn: 0.0558511	total: 12.2s	remaining: 17.3s
332:	learn: 0.0558497	total: 12.3s	remaining: 17.2s
333:	learn: 0.0558487	total: 12.3s	remaining: 17.2s
334:	learn: 0.0558471	total: 12.4s	remaining: 17.2s
335:	learn: 0.0558450	total: 12.5s	remaining: 17.2s
336:	learn: 0.0558440	total: 12.5s	remaining: 17.2s
337:	learn: 0.0558425	total: 12.6s	remaining: 17.2s
338:	learn: 0.0558414	total: 12.6s	remaining: 17.1s
339:	learn: 0.0558400	total: 12.7s	remaining: 17.1s
340:	learn: 0.0558388	total: 12.7s	remaining: 17.1s
341:	learn: 0.0558377	total: 12.8s	remaining: 17.1s
342:	learn: 0.0558364	total: 12.8s	remaining: 17s
343:	learn: 0.0558353	total: 12.8s	remaining: 17s
344:	learn: 0.0558342	total: 12.9s	remaining: 17s
345:	learn: 0.0558327	total: 12.9s	remaining: 16.9s
346:	learn: 0.0558310	total: 12.9s	remaining: 16.9s
347:	learn: 0.0558300	total: 13s	remaining: 16.9s
348:	learn: 0.0558286	total: 13s	remaining: 16.8s
349:	learn: 0.0558273	total: 13s	remaining: 16.8s
350:	learn: 0.0558260	total: 13.1s	remaining: 16.7s
351:	learn: 0.0558246	total: 13.1s	remaining: 16.7s
352:	learn: 0.0558240	total: 13.2s	remaining: 16.7s
353:	learn: 0.0558217	total: 13.2s	remaining: 16.6s
354:	learn: 0.0558199	total: 13.2s	remaining: 16.6s
355:	learn: 0.0558150	total: 13.3s	remaining: 16.6s
356:	learn: 0.0558119	total: 13.3s	remaining: 16.5s
357:	learn: 0.0558099	total: 13.4s	remaining: 16.5s
358:	learn: 0.0558087	total: 13.4s	remaining: 16.5s
359:	learn: 0.0558077	total: 13.4s	remaining: 16.4s
360:	learn: 0.0558067	total: 13.5s	remaining: 16.4s
361:	learn: 0.0558056	total: 13.5s	remaining: 16.3s
362:	learn: 0.0558045	total: 13.5s	remaining: 16.3s
363:	learn: 0.0558022	total: 13.6s	remaining: 16.3s
364:	learn: 0.0557983	total: 13.6s	remaining: 16.2s
365:	learn: 0.0557976	total: 13.7s	remaining: 16.2s
366:	learn: 0.0557962	total: 13.7s	remaining: 16.2s
367:	learn: 0.0557950	total: 13.7s	remaining: 16.1s
368:	learn: 0.0557938	total: 13.8s	remaining: 16.1s
369:	learn: 0.0557929	total: 13.8s	remaining: 16s
370:	learn: 0.0557916	total: 13.8s	remaining: 16s
371:	learn: 0.0557906	total: 13.9s	remaining: 16s
372:	learn: 0.0557898	total: 13.9s	remaining: 15.9s
373:	learn: 0.0557889	total: 14s	remaining: 15.9s
374:	learn: 0.0557878	total: 14s	remaining: 15.9s
375:	learn: 0.0557851	total: 14s	remaining: 15.8s
376:	learn: 0.0557826	total: 14.1s	remaining: 15.8s
377:	learn: 0.0557812	total: 14.1s	remaining: 15.8s
378:	learn: 0.0557798	total: 14.2s	remaining: 15.7s
379:	learn: 0.0557786	total: 14.2s	remaining: 15.7s
380:	learn: 0.0557769	total: 14.2s	remaining: 15.7s
381:	learn: 0.0557750	total: 14.3s	remaining: 15.6s
382:	learn: 0.0557736	total: 14.3s	remaining: 15.6s
383:	learn: 0.0557716	total: 14.3s	remaining: 15.5s
384:	learn: 0.0557707	total: 14.4s	remaining: 15.5s
385:	learn: 0.0557693	total: 14.4s	remaining: 15.5s
386:	learn: 0.0557685	total: 14.4s	remaining: 15.4s
387:	learn: 0.0557672	total: 14.5s	remaining: 15.4s
388:	learn: 0.0557659	total: 14.5s	remaining: 15.3s

In [18]:
test_data = pd.read_csv('/kaggle/input/playground-series-s5e10/test.csv')
test_data

,id,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents
0,517754,highway,2,0.34,45,night,clear,True,True,afternoon,True,True,1
1,517755,urban,3,0.04,45,dim,foggy,True,False,afternoon,True,False,0
2,517756,urban,2,0.59,35,dim,clear,True,False,afternoon,True,True,1
3,517757,rural,4,0.95,35,daylight,rainy,False,False,afternoon,False,False,2
4,517758,highway,2,0.86,35,daylight,clear,True,False,evening,False,True,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
172580,690334,rural,2,0.01,45,dim,rainy,False,False,afternoon,True,True,2
172581,690335,rural,1,0.74,70,daylight,foggy,False,True,afternoon,False,False,2
172582,690336,urban,2,0.14,70,dim,clear,False,False,evening,True,True,1
172583,690337,urban,1,0.09,45,daylight,foggy,True,True,morning,False,True,0
172584,690338,highway,1,0.63,35,night,foggy,True,False,evening,False,False,0

In [20]:
ids = test_data['id']
Xt_data = test_data.drop(['id'], axis=1)
Xt_data = ctx.transform(Xt_data)

In [21]:
yt_pred = cat.predict(Xt_data)
np.savetxt('output.csv', np.column_stack((ids, yt_pred)), delimiter=',', comments='', header='id,accident_risk', fmt=['%d', '%.2f'])

In [127]:
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print('MSE for catboost:', mean_squared_error(y_test, y_pred))
print('R2 for catboost:', r2_score(y_test, y_pred))

MSE for catboost: 0.0035317500530205807
R2 for catboost: 0.8720945528926276

In [128]:
yt_pred = rf.predict(Xt_data)
np.savetxt('output2.csv', np.column_stack((ids, yt_pred)), delimiter=',', comments='', header='id,accident_risk', fmt=['%d', '%.2f'])